### ISSUE TITLE
Freyja plot fails when single value in abundances column

### ISSUE THREAD

**Issue by susancollins** [andersen-lab/Freyja#105]
After encountering the following error a few times, I did some digging:
<img width="911" alt="Screen Shot 2022-12-07 at 10 40 37 AM" src="https://user-images.githubusercontent.com/54604213/206223557-5bc4eeb6-d691-4d33-a0b1-980fa2fb4493.png">

It seems that when pandas encounters only single values in the 'abundances' column of the aggregate file, the values are read as floats instead of strings. However, when one of the samples in the aggregate file contains multiple abundances, the values are read as intended (strings).

Perhaps sanitizing the abundances column with something like:
`agg_df['abundances'] = agg_df['abundances'].astype(str)`

Will do the trick

**Comment by joshuailevy** [comment]
Hey @susancollins! Sorry for the delay, just worked this into Freyja. Any chance you have an example aggregate file so I can make sure it's working properly? Thanks!

**Comment by susancollins** [comment]
Awesome! Here is a test file that fails to plot for me:

[freyja_test_agg.txt](https://github.com/andersen-lab/Freyja/files/10344686/freyja_test_agg.txt)

**Comment by susancollins** [comment]
Thanks so much Josh!
