### ISSUE TITLE
Possible Error in BQ.1.1 calls

### ISSUE THREAD

**Issue by ParceyM** [andersen-lab/Freyja#106]
After several experimental runs today I noticed BQ.1.1. wasn't being called while its children, such as BQ.1.1.15, were. Within the barcoding file I found BQ.1.1 incorrectly associated with C15240T. I corrected manually on my side, but I heard a colleague say something similar (BQ.1.1 not being called) so I thought it was worth mentioning.

**Comment by joshuailevy** [comment]
Interesting. It looks like something has changed in the UShER tree in the last week or two, I'm not quite sure what is going on there. I just did a quick check, and the mutation sequence leading to BQ.1.1 in a tree from a few weeks back didn't include 15240T, but now does... and as you suggest 15240T is not present in descendants of BQ.1.1. 

I just checked directly with the UShER tree, and the path looks like this (15240T occurs, then reverts, then occurs again): 
```BQ.1.1	node_1016174	 > C14408T > C241T > C3037T > A23403G > G28881A > G28882A,G28883C > C21846T > C10029T,C10449A,C15240T,C21762T,A23055G,A23063T,T23075C,C23525T,T23599G,C23604A,C23854A,G23948T,C24130A,C25000T,C26270T,A27259C,C27807T,A28271T,C28311T > G22578A,T22673C,C22674T,T22679C,C22686T,A23040G,A24424T,T24469A,C25584T > A18163G,G22992A,C22995A,A23013C,C26577G > G26709A > T22882G > G22813T,A26530G > A24130C > T13195C,T15240C,C22673T,G22775A,G26530A > G4184A,G10447A,C12880T,C13195T,C15714T > T670G,C4321T,C9534T,C10198T,C17410T,C19955T,A20055G,T21762C,T21846C,A22786C,A29510C > C9344T,C9866T,C21618T,T22200G,A22688G,C26060T,C26858T,G27382C,A27383T,T27384C > A9424G > C2790T > T9866C > T26858C > C27259A,C27382G > T27383A,C27384T > G23040A > T23018G > T22917G > G12160A > G26529A > C27889T > C1931A > G28681T > G16935A > T2954C > C11750T > C28312T > A22893C > T14257C > T22942A > G22599C > C15240T,A17039G ```

Maybe @AngieHinrichs has an idea how 15240T might have popped up in the path again?

**Comment by AngieHinrichs** [comment]
Yes, that's a problem with the annotation on the [public tree](https://hgdownload.gi.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/) and I will try to fix it ASAP.  Thanks for tagging me!

[Details: There's a small number of sequences with ... > T22942A > G22599C > C15240T in the full tree, and a small number of sequences with all those mutations and A17039G, and a few weeks ago matOptimize decided to move all of BQ.1.1 (which had been .. > T22942A > G22599C > A17039G) to ... > T22942A > G22599C > C15240T > A17039G > T15240C.  About a week ago, the public tree changed from ... > C15240T > A17039G > T15240C (where BQ.1.1 had been annotated) to > C15240T,A17039G > T15240C -- i.e. C15240T and A17039G were now annotated on the same node.  Our annotation-labeling algorithm is less picky about the final node on the path, so it ignored the C15240T when it saw that the node had A17039G, but that is definitely not what we want.  So I will constrain it to require 15240=C when placing the BQ.1.1 label.  I will also see if I can convince matOptimize not to put C15240T ahead of A17039G.]

**Comment by joshuailevy** [comment]
Looks like the issue has now been fixed in the usher public tree. Thanks @AngieHinrichs!
