### ISSUE TITLE
How Freyja determine the lineages

### ISSUE THREAD

**Issue by pratibha-kadam** [andersen-lab/Freyja#107]
Hello There,

I am using Freyja for wastewater sample analysis. I need one help. When I generate mutations using ivar it is in very few numbers like Ex- 4 from Nanopore sequencing and I have this doubt that when we compare the sample lineage with original Wuhan strain it has lots of mutatioins in the variant.tsv file from Freyja.

 Why this mutation difference is there from ivar and Freyja ? 

and also the alternate depth is very low for most of the mutations in variant.tsv file from Freyja Ex-1. So, R u also considering the very low depth mutation like depth 1 for defining lineage  ?

Can you tell me if I have to consider the mutations which mutations I shall consider with from variants.tsv file ??

Please let me know ASAP
Thanks

**Comment by joshuailevy** [comment]
Hi!
Freyja considers all SNVs within a given file, while iVar by default will only return SNVs that happen at 3% frequency or greater. Freyja uses a depth weighted approach, so while SNVs with just a few reads are considered, they are given less weight than other mutations with greater sequencing depth. 
Best, 
Josh
