### ISSUE TITLE
Barcode versioning

### ISSUE THREAD

**Issue by hsnguyen** [andersen-lab/Freyja#117]
Hi team,
I think it'd be great if we can track the version of the barcodes used by Freyja demix, especially for the pipeline always running `freyja update` before demixing.
Thanks.

**Comment by joshuailevy** [comment]
Hi @hsnguyen, 
I agree, super important. At the moment, we do have all barcodes versioned via the commit history on github (see here: https://github.com/andersen-lab/Freyja/commits/main/freyja/data/usher_barcodes.csv). We could certainly make this a bit easier for users to access and use though. Perhaps adding options to check the barcode date and/or download a specific day's barcode via the CLI would help with this?  Happy to try out any suggestions you've got. 
Josh

**Comment by hsnguyen** [comment]
Thanks @joshuailevy, that'd be great.
Yeah now I'm using the commit history for the versions and some manual work is enough for this purpose but CLI is definitely making life easier. 
Even fancier, hopefully we can have somethings like [nextclade-data](https://github.com/nextstrain/nextclade_data), a separate git repo for the data releases. The release tag can simply be the built timestamp and the notes contain information like newly important sub-lineages being added, the usher tree version links to it...

**Comment by joshuailevy** [comment]
Hey @hsnguyen, I put together a comparable data repository now available in [Freyja-data](https://github.com/andersen-lab/Freyja-data). Whenever the barcode library is updated, a corresponding update will be made there and historical barcodes/metadata will appear in the "history" folders. Newly added lineages are listed in the "barcode_diffs" folder. 

Let me know what you think. Happy to accommodate further suggestions!

**Comment by hsnguyen** [comment]
Is it an easy way to print out also the current barcode version from command line, e.g. like from `freyja --version` ?
The idea is to record both the versions of the software and data used for a particular run for the sake of reproducibility later.
Thanks,

**Comment by joshuailevy** [comment]
Ah, yes. Hadn't yet merged that branch, but just did now. You should be able to run `freyja demix --version` and you'll get out the current barcode version. Thanks again for the suggestions!
