### ISSUE TITLE
Same results for different samples

### ISSUE THREAD

**Issue by mikal16** [andersen-lab/Freyja#118]
Hi there,

I'm running freyja on wastewater samples and the package is working very well with all my steps having run smoothly along with the steps to generate the graphs. However, my main issue seems to be that my results don't make sense. I'm running Freyja on a number of different wastewater samples from very different timepoints and locations, but I seem to be getting the same exact results for each sample. Not sure what might be going on here, but any insight would help.

Thanks very much in advance,

Mikal

[aggregated_plot_lineages.pdf](https://github.com/andersen-lab/Freyja/files/10886720/aggregated_plot_lineages.pdf)

**Comment by joshuailevy** [comment]
Hi Mikal, 

I'm not entirely sure, but it looks like you might have an issue with your alignment causing the indexing to be off. Are you aligning to the Hu-1 genome? 

If you want to send an example bam file my way, I can take a closer look. 

Josh

**Comment by mikal16** [comment]
Hi Josh,

Thanks so much for the quick response. I think that actually may be the problem.. Let me align my sequences again to the Hu-1 genome and give that a go and report back with whether that fixes the issue.

This may be a dumb question, but would you happen to have the corresponding gtf annotation file for the Hu-1 genome. I found one on ensembl, but I'm not sure if it's the correct one.

Thanks so much for your help!

Mikal

**Comment by mikal16** [comment]
Issue solved with the proper alignment, thank you!
