### ISSUE TITLE
freyja plot --config is throwing error

### ISSUE THREAD

**Issue by mikal16** [andersen-lab/Freyja#121]
Hi there,

This is probably a very dumb question, but I'm trying to use the --config option for freyja plot, however I'm getting this error : 

Error: No such option: --config

My code works fine when I don't try to use the config option, however I'm just using it to edit the colors of my lineages.

Thanks very much in advance!

Mikal

**Comment by joshuailevy** [comment]
Hi Mikal! You've got the right idea, but need to specify an associated config file along with your plot. Here's an example one that makes separate groups for Alpha and Delta lineages: https://github.com/andersen-lab/Freyja/blob/main/freyja/data/plot_config.yml

**Comment by mikal16** [comment]
Thanks so much for the quick response! Sorry, I should've included the full line of code.

freyja plot aggregated_output.tsv --output aggregated_plot_lineages.pdf --times times_metadata.csv --interval D --config plot_config.yml 

And then this is the full error I get

Usage: freyja plot [OPTIONS] AGG_RESULTS
Try 'freyja plot --help' for help.

Error: No such option: --config

And I just added a quick screenshot of how my config file looks like. 

But, I think my problem here is that --config isn't being recognized as an executable with frejya plot for some reason.

<img width="937" alt="Screen Shot 2023-03-13 at 9 12 39 PM" src="https://user-images.githubusercontent.com/66184173/224866884-358dc583-2b6e-4b4c-b765-a14ddc98e3d9.png">
