### ISSUE TITLE
Error: No such command 'extract'

### ISSUE THREAD

**Issue by danstrange** [andersen-lab/Freyja#122]
Hi,

Interested in trying out the freyja read analysis tools but the 'extract' and 'filter' commands are not present.. Is this feature still available? Below are the freyja commands currently available to me.

(freyja-env) xxxxxxxx$ freyja --help
Usage: freyja [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  aggregate
  boot
  dash
  demix
  plot
  relgrowthrate
  update
  variants
(freyja-env) xxxxxxxx$

**Comment by joshuailevy** [comment]
Hey @strangemandan, 
At the moment these functions are not yet available via conda and are only available on github. We're planning to release a new version of Freyja in the next week or so that will include them (and be on conda). 
Josh

**Comment by strangemandan** [comment]
Got it. Thanks, Josh.
-Dan
