### ISSUE TITLE
Freyja plot (smoothing)

### ISSUE THREAD

**Issue by mikal16** [andersen-lab/Freyja#124]
Hi there,

This may seem like a trivial question, but how can you add the smoothing effect when using freyja plot?

Thanks in advance,

Mikal

**Comment by joshuailevy** [comment]
Hi Mikal, 

Sorry for the delay, it seems I missed this. You should be able to control the smoothing when using the ```--interval D``` option by setting the ```--windowsize``` parameter. This will by default use a rolling average filtering method with the specified width (default the value is 14). 

Josh

**Comment by mikal16** [comment]
No worries at all and I ended up playing around with the window size and it looks much better. Thanks a ton!
