### ISSUE TITLE
Freyja plot not generating proper plots

### ISSUE THREAD

**Issue by pratibha-kadam** [andersen-lab/Freyja#128]
Hey There,
I have been using freyja since long time. But this new version V.1.4.2 somehow not able to plot the many samples together. and even if it does the color coding is not accurate.

Command:
freyja plot all_batch_6_reanalysed-aggregated.tsv --lineages --mincov 0 --config config.yml --output batch_6.pdf

Uploaded the plot here. please let me know where it is wrong
![Screenshot from 2023-04-20 16-40-05](https://user-images.githubusercontent.com/88572259/233349266-fed18abf-242c-437f-962c-b5b54a91f56a.png)

**Comment by joshuailevy** [comment]
Thanks for bringing this up @pratibha-kadam! This has been sorted and will be incorporated into the main branch (and will be in the next release)
