### ISSUE TITLE
Generating "curated_lineages.json" and "lineages.yml" files for creating barcodes

### ISSUE THREAD

**Issue by pgangwar-ucsd** [andersen-lab/Freyja#129]
Hi, 

I was trying to use Freyja on some older SARS-CoV2 tree and realized that apart from an older phylogenetic tree file I might also have to generate older "curated_lineages.json" and "lineages.yml" files as well. Could you please guide me on how to generate these files to ensure that data generated by Freyja is consistent?

Thanks,

**Comment by joshuailevy** [comment]
Hi  @pgangwar-ucsd, 

If you want a copy of the older ```curated_lineages.json``` file, you should be able to pull that from the github commit history [here](https://github.com/outbreak-info/outbreak.info/commits/master/web/src/assets/genomics/curated_lineages.json). The ```lineages.yml``` file just stores the complete hierarchy and adds as new lineages are designated, so you should be able to use a current version of that. 

Best, 
Josh
