### ISSUE TITLE
TreeMarkovJumpHistoryAnalyzer, how to use?

### ISSUE THREAD

**Issue by abulenciamiguel** [andersen-lab/Freyja#136]
I would just like to know how to run the TreeMarkovJumpHistoryAnalyzer.java? 

Thank you.

**Comment by joshuailevy** [comment]
Hi @abulenciamiguel, I think this is more of a BEAST question rather than Freyja. Might be better to address this here: https://github.com/beast-dev/beast-mcmc

Best, 
Josh
