### ISSUE TITLE
Strategy for using 'custom' summarised lineage groups when demixing?

### ISSUE THREAD

**Issue by AliceMichie93** [andersen-lab/Freyja#138]
Hi there,

Forgive me if this is a silly question, or something that has already been addressed in previous requests.

Currently when we demix our wastewater sequence data, the minor lineages are 'summarised' into broad lineage groups: XBB.1.5*, BA.2.75*, BA.5*, 'Omicron' and 'Other'. 
Ideally, we would like to have additional lineage groupings, to include lineage 'clusters' that are currently more 'clinically relevant' (such as XBB.1.9*, XBB.1.16*, etc).

Can you offer any advice on how to go about doing this? I have tried using the dash function to analyse the aggregate data (with the default lineage summaries) with a custom plot config file with our desired lineage groupings, but the resulting plot had the same, default lineage groupings

Thanks so much,
Alice

**Comment by joshuailevy** [comment]
Hi Alice! 

Not a silly question at all! The "summarized" groupings are just intended as a default grouping of key VOCs, but as you suggest, they are not necessarily as descriptive as you might like. 

The config option should take care of this, provided the correct formatting is used (for both dash and plot). If you can share a copy of your config file I can try to figure out what's going on. 

If you're processing these data separately anyway, you can access the relevant parsing functions directly from python: https://github.com/andersen-lab/Freyja/blob/5fd8460098db9455dfe4c251eea911bfd4433e4a/freyja/utils.py#L186 

Josh

**Comment by joshuailevy** [comment]
In case it's helpful, here's a version more specific to today's concerns :) 
[plot_config.yml.txt](https://github.com/andersen-lab/Freyja/files/11512128/plot_config.yml.txt)
