### ISSUE TITLE
Freyja Plot Error:AttributeError: 'DataFrame' object has no attribute 'append'

### ISSUE THREAD

**Issue by pratibha-kadam** [andersen-lab/Freyja#142]
Hello There,

I got a small error for plotting the lineages.

Freyja (V.1.4.3)

Here is the command I use:
 freyja plot --mincov 0 --lineages FMR-B6-67a-aggregated.tsv > lineages.pdf

Attaching the aggregate.tsv but in xlsx format.
[FMR-B6-67a-aggregated.xlsx](https://github.com/andersen-lab/Freyja/files/11528025/FMR-B6-67a-aggregated.xlsx)

PFA the screenshot of the error
![Screenshot from 2023-05-22 12-26-35](https://github.com/andersen-lab/Freyja/assets/88572259/87a3704f-6526-4f07-9b54-dba23478f268)

Please advice me further.
Lots of Thanks.

**Comment by dylanpilz** [comment]
Hey @pratibha-kadam,

We addressed this issue in #139 and will be including this fix in the next freyja release. In the mean time, you should be able to clone the current repo and run `pip install -e .` from the Freyja directory. Otherwise you could revert to pandas version 1.5 or earlier.

Dylan
