### ISSUE TITLE
Freyja plot

### ISSUE THREAD

**Issue by mikal16** [andersen-lab/Freyja#148]
Hi there,

I am trying to run freyja plot and I am getting this error.
<img width="891" alt="Screen Shot 2023-06-07 at 10 46 42 AM" src="https://github.com/andersen-lab/Freyja/assets/66184173/8e2ecd25-1090-4f7e-ac61-6a53b081b3a1">

After going through my aggregated file, I realize it is because all my samples have a very low coverage of 3.5, which is why it won't run. However, it seems very odd to me that all my samples would have such low coverage. I followed the steps to generate the bam files for processing step by step, and was just wondering if you might have any insight on why I would be seeing such bad coverage.

Thanks very much in advance!

Mikal

**Comment by mikal16** [comment]
Sorry, I should also mention that when I used samtools to calculate my coverage using a command such as this one: samtools depth -a  *bamfile*  |  awk '{sum+=$3} END { print "Average = ",sum/NR}' 
my coverage seemed to look good for almost all my samples (attached).

[coverage.txt](https://github.com/andersen-lab/Freyja/files/11679136/coverage.txt)

Thanks again,

Mikal

**Comment by joshuailevy** [comment]
Hi Mikal, 

I think you're using a slightly different definition of coverage (unfortunately, there's a handful of different definitions out there). Freyja returns the fraction of sites with greater than 10 reads, but your method calculates the average number of reads per site (since sequencing depth is often highly non-uniform across sites, this readout can be a bit misleading).

Josh

**Comment by joshuailevy** [comment]
That's somewhat strange. Freyja should produce a separate coverage for each sample. Are you doing whole genome sequencing? If you are doing spike only seq, this could potentially happen.

**Comment by mikal16** [comment]
I'm doing whole genome sequencing. But I'm finding that for each folder with multiple samples that I'm processing, I'm getting the same coverage for every single sample, which is very odd.

Let me know if anything I could send could help troubleshoot this.

Thanks again,

Mikal

**Comment by joshuailevy** [comment]
I'd be happy to take a look at a few example bam files if you want to send them! 

Josh

**Comment by mikal16** [comment]
Awesome, yes, the weird thing is I ran this twice and the first time it worked not detecting any issues in quality, but the second time it was showing problems with the quality. It doesn't seem to let me attach bam files here, let me know if you'd like me to email a few.

Thanks again!

Mikal

**Comment by joshuailevy** [comment]
Ah, sorry. You'd have to save them with a txt extension to drop them here. You can also just send them to me at jolevy@scripps.edu
