### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by PlushZ** [andersen-lab/Freyja#149]
We added Freyja to Galaxy, and now we need to update Freyja on Galaxy. Since the last 1.4.3 release had a plot error that was fixed in subsequent commits, I am curious about when you plan to release the next version. We would be delighted to update the Galaxy tool as soon as possible and incorporate it into our workflows. Thanks

**Comment by joshuailevy** [comment]
Hi @PlushZ!

Thanks for reaching out. We were thinking of adding an additional feature into the next release, but a few things came up and we haven't yet gotten around to it. We'll make a new release in a bit!

Josh

**Comment by PlushZ** [comment]
Thank you so much @joshuailevy
