### ISSUE TITLE
Identical Abundance Result

### ISSUE THREAD

**Issue by whottel** [andersen-lab/Freyja#154]
Hello,

On a few lower quality samples, I have noticed that the same abundance result is recorded across several lineage (please find attached example).
[S190_demix.txt](https://github.com/andersen-lab/Freyja/files/11824425/S190_demix.txt)

Any thoughts on what might be causing this?

Thanks,
Wes

**Comment by joshuailevy** [comment]
Hey Wes, 

Sorry for the delay. It looks like given the available sequencing coverage, Freyja is assigning equal likelihood to each of those XBB.1.5 lineages (which it represents by assigning equal fractions to each lineage). We are actually about to release some functionality that will automatically group lineages that are indistinguishable given the available genome coverage that will help out with this case (as well as some of the convergence errors that can happen as a result of these identifiability issues). 

Josh

**Comment by whottel** [comment]
Hi Josh,

Thanks for the response, I will be on the lookout for the udpated version.

-Wes
