### ISSUE TITLE
Output unclear

### ISSUE THREAD

**Issue by lskatz** [andersen-lab/Freyja#16]
Hi, Thank you for having this software open to the public.  Could you document what the output of the demix step is?  This is one of mine.  I am unclear on what the `summarized` line gives apart from `lineages`, and I am unclear what `resid` means.  Thank you!

```
        /tmp/10192355.1.all.q/tmp.VIFAQ9Hmvc10192355/SRR15383942.freyja/freyja.variants.tsv
summarized      [('Delta', 0.989275601990426), ('Other', 0.004566639999873597)]
lineages        ['B.1.617.2' 'AY.6' 'AY.20' 'B.1.1.434' 'B.1.177.2' 'AY.23' 'B.1.127']
abundances      "[0.97995719 0.00479616 0.00320588 0.00207684 0.00145138 0.00131637
 0.00103842]"
resid   2.1489096407905945
```

**Comment by joshuailevy** [comment]
Hi!  Thanks for pointing out the lack of documentation on the output format! 

The ```summarized``` line provides a sum of the abundances of all lineages within the WHO classification (e.g. abundance levels of B.1.1.7 and Q.* are all summed for alpha, B.1.617.2 and AY.* for delta). If lineages do not have a WHO classification, they are grouped into "other".

```resid``` is the residual from the weighted least absolute deviation regression problem used to recover the underlying lineages. In some cases it can be useful to identify how well the estimated model represents the data, but can be misleading when sequencing data is noisy. Hoping to roll out some new quality metrics soon (e.g. bootstrap CI estimates). 

I'll add documentation on this sometime today. 

Josh

**Comment by lskatz** [comment]
Thank you!  Keep up the good work!  The world needs reliable software to do metagenomic analysis!

**Comment by joshuailevy** [comment]
Added documentation. Thanks again.
