### ISSUE TITLE
Allow user to pass in lineages.yml

### ISSUE THREAD

**Issue by wutron** [andersen-lab/Freyja#165]
Can `lineages.yml` be passed through an argument, perhaps `--hierarchy`?  This functionality would match allowing the user to pass through `--barcodes` and `--meta`.  From a cursory look, `demix`, `boot`, `plot`, and `relgrowthrate` use this file.

**Comment by ktmeaton** [comment]
Just giving this issue a bump. This gets me everytime I upgrade to a new `--barcodes` and `--meta`, but forget to run `freyja update` to make sure the internal `lineages.yml` is synchronized 😅

**Comment by joshuailevy** [comment]
Thanks for the reminder! Was just looking back into this (sorry for the delay!!)- we'll have it added in soon!
