### ISSUE TITLE
freyja plot doesn't deal with empty pandas df

### ISSUE THREAD

**Issue by PlushZ** [andersen-lab/Freyja#166]
When attempting to apply the --mincov parameter for the 'freyja plot' and no samples meet the minimum coverage value, Freyja throws a pandas error. I wanted to inquire whether you are aware of this issue and if there are any plans to address it in the near future?
Thanks.

Polina

**Comment by joshuailevy** [comment]
Hi @PlushZ, this is a good point. While I was aware of the issue, I hadn't gotten around to incorporating a more specific warning/error message to guide the user. I'll make sure to add this into the next release. 
Josh
