### ISSUE TITLE
colors for plots with day interval

### ISSUE THREAD

**Issue by karenbobier** [andersen-lab/Freyja#17]
Hello, Thanks for making this software available. 

I am just trying out Freyja while trying to figure out how to analyze our covid ww sequence data. I noticed the plots for daily intervals only have a 10 color pallet that is being used, and if there are >10 lineages the colors repeat. The plots for just lineage abundance or monthly intervals have more colors. I think it might be the same 10 color pallet but with 2 shades per color. Is it possible to add additional colors to the plot when its plotted by day intervals?

Example plot with daily interval with 14 day window, colors repeat:
```freyja plot Freyja/freyja_aggregate.tsv --output Freyja/output_summary_plot_by_day.pdf --times Freyja/sample_dates.csv --interval D --windowsize 14```
[output_summary_plot_by_14day.pdf](https://github.com/andersen-lab/Freyja/files/7781985/output_summary_plot_by_14day.pdf)

Example plot with monthly interval, no repeating colors:
```freyja plot Freyja/freyja_aggregate.tsv --output Freyja/output_lineages_plot_by_date.pdf --times Freyja/sample_dates.csv --interval MS --lineages```
[output_lineages_plot_by_month.pdf](https://github.com/andersen-lab/Freyja/files/7781995/output_lineages_plot_by_month.pdf)

Thanks!

**Comment by joshuailevy** [comment]
Hi! Thanks for pointing this out. I think a reasonable solution to this would be to allow for a users to include a ```--colors colors.txt```. If you have something else in mind, I'd be happy to try out other approaches.  

 I'll plan to include something along these lines in the next release. 
Thanks! 
Josh
