### ISSUE TITLE
set reference genome and annoation for `freyja extract`

### ISSUE THREAD

**Issue by dwinter** [andersen-lab/Freyja#170]
May thanks for this very useful tool!

We are now using the read analysis tools in freyja to go hunting for mutations of interest ,and ran into the issue that  `freyja extract` is expecting the `NC_045512.2`. Would it be possible to make the reference genome and annotation optional arguments as theya re for `covariants`? 

(Not a burning issue, at it's easiy enough to re-run the alignments)

**Comment by dylanpilz** [comment]
Hey,

Certainly! It actually much simpler to pull the reference name directly from the input bam file as in `covariants`. I'll make this change to `extract` and `filter` and include it in the next release.

-Dylan
