### ISSUE TITLE
lineage Misc?

### ISSUE THREAD

**Issue by ybdong919** [andersen-lab/Freyja#171]
what is the meaning of lineage "Misc" in the out file of freyja?

**Comment by dylanpilz** [comment]
When calling `freyja demix` using the `--depthcutoff` option, sites with coverage below the user-specified cutoff value are excluded from the barcodes matrix. This then results in some lineage having identical barcodes, which is then resolved via shared ancestry between "identical" lineages. In some cases, (typically with poor coverage and high `depthcutoff`, it is impossible to find a clear recent common ancestor for these groups of lineages. Most commonly, this occurs when multiple distinct recombinant lineages are grouped together, or recombinant lineages are grouped with non-recombinant lineages. In such cases, we find it most informative to avoid checking the recombinant parents for shared ancestry, and instead designate the group with "Misc".

To see how the original lineages have been grouped into higher-order classifications, you can check the `collapsed_lineages.yml` file that is produced when running `demix` with the `depthcutoff` option.

Let me know if you have any further questions or if I can clarify anything!
-Dylan

**Comment by tibitoy** [comment]
What if you get this result without using the -depthcutoff option? I've seen " miscBA1BA2Pre10k" or "miscDeltaBA1Post11k" in some of my samples but I don't use that option. Not sure how to interpret this.

**Comment by joshuailevy** [comment]
Oh, this is a slightly different "misc" actually, resulting from some of the naming conventions used in the UShER tree. These "misc" lineages are undesignated sub-clades that have been annotated in the global phylogeny. 

If you're using a more recent version of Freyja, these lineage barcodes should be dropped by default. However, if you're constructing your own barcodes (either via an older version of Freyja or using the `--buildlocal` option) with the `--noncl` flag, these will still pop up.

**Comment by ybdong919** [comment]
> et this result

I get "misc" when use --depthcutoff

**Comment by joshuailevy** [comment]
Running `freyja update` will only update the barcodes, it won't actually update Freyja itself. To do that you'll need to update the package, which will depend on how you installed Freyja. Assuming you installed via conda, you'll just need to install a more recent version of the package (most recent release is v1.4.5).

I'll close this issue, but let us know if that doesn't work for you!
