### ISSUE TITLE
how to update freyja from 1.3 to 1.4.5

### ISSUE THREAD

**Issue by ybdong919** [andersen-lab/Freyja#175]

**Comment by ybdong919** [comment]
When I use conda install freyja=1.4.5, I get errors below:
UnsatisfiableError: The following specifications were found to be incompatible with each other:

 

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

 

  - feature:/linux-64::__glibc==2.17=0
  - feature:/linux-64::__unix==0=0
  - feature:|@/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__unix==0=0
  - freyja=1.4.5 -> click -> __unix
  - freyja=1.4.5 -> click -> __win

 

Your installed version is: 2.17

**Comment by joshuailevy** [comment]
I think is just a conda error. Looks like it's finding some conflicts but failing to properly report what's going on. The easiest thing to do would be to just create a fresh environment with the needed packages, see: https://stackoverflow.com/questions/71678461/conda-unsatisfiableerror-with-linux64-and-glibc
