### ISSUE TITLE
Abundance 100%

### ISSUE THREAD

**Issue by Linnet111** [andersen-lab/Freyja#177]
Hi Josh,

Just had a quick question- does the abundance of the lineages have to add up to 100% in total for a particular sample? Is the algorithm created that way or are variations in the total abundance expected?

Thank You

Kind regards
Linnet Immaraj

**Comment by joshuailevy** [comment]
Hi Linnet, 

When running Freyja using the default parameters, lineage frequencies less than the threshold (0.1%) will not be included in the output, so as to not report tons of low level false positives. As a result, the sum may not always add up to 100%. You can adjust this parameter using the `--eps` command though. Setting it to something small should lead to the sum equalling 100%. 

Best, 
Josh

**Comment by Linnet111** [comment]
Thank You! Appreciated!

**Comment by joshuailevy** [comment]
No problem! :)
