### ISSUE TITLE
Pandas update breaks demixing

### ISSUE THREAD

**Issue by gabimuir** [andersen-lab/Freyja#179]
Upgrading pandas from version 2.0.3 to the newest 2.1.0 gives a TypeError in deconvolution.

The error is:
> File "/home/ubuntu/miniconda3/envs/freyja/lib/python3.10/site-packages/freyja/sample_deconv.py", line 71, in build_mix_and_depth_arrays
>     df['mutName'] = df['REF'] + df['POS'].astype(str) + df['ALT']
> ...
> TypeError: unsupported operand type(s) for +: 'float' and 'str'

Downgrading back to pandas 2.0.3 fixed the issue

**Comment by dylanpilz** [comment]
Would you mind sharing the steps to reproduce the error (i.e. command, freyja version, input files)? If you prefer, you're welcome to reach out via email (dpilz@scripps.edu) in case you'd rather not post the files publicly.

**Comment by dylanpilz** [comment]
Closing as stale

**Comment by dylanpilz** [comment]
Closing as stale
