### ISSUE TITLE
Potential bug in sorting code for covariants function

### ISSUE THREAD

**Issue by JHarrisonEcoEvo** [andersen-lab/Freyja#181]
Hi, I was checking out the code for the covariants function and found this passage, starting at line 685:

    if sort_by.lower() == 'count':
        df = df.sort_values('Count', ascending=False)
    elif sort_by.lower() == 'freq':
        df = df.sort_values('Count', ascending=False)

Just checking to see if this should specify different sorting criteria. Perhaps I am missing something elsewhere in the code, but this looked like maybe a typo, since the statement following the conditional is the same. Cheers

**Comment by dylanpilz** [comment]
Hey @JHarrisonEcoEvo, nice catch! I seem to have missed this since `plot-covariants` sorts by frequency by default, but `covariants` should obviously sort the values correctly by the user-defined parameter. Will put out a fix soon.

-Dylan
