### ISSUE TITLE
Reduce runtime

### ISSUE THREAD

**Issue by erinyoung** [andersen-lab/Freyja#184]
I like using Freyja in my SARS-CoV-2 nextflow workflows. I am encountering issues, however, with how long Freyja takes to run. 

Do you have tips or suggestions on how to reduce the time that Freyja variants demix or boot takes to run?

**Comment by joshuailevy** [comment]
Hi @erinyoung! 

Glad you've been enjoying using Freyja! The demix step has definitely been taking a bit longer as of late now that the list of candidate lineages has ballooned. I'd worked on a few tricks to speed that up a while back (e.g., on dropping lineages with few signature mutations present before solving the demixing problem), but they didn't quite make it into the codebase. Of course using a barcode with only recent lineages will speed things up, but in general I wouldn't recommend that as you risk missing things like cryptic circulation. 

The variants step generally takes more time overall- and I haven't really tried speeding that one up- I'll take a hack at that next week. Just to check- is all of your sequencing just SARS-CoV-2 amplicon seq? Or do you have multiple schemes/references? 

Best, 
Josh

**Comment by erinyoung** [comment]
Just one scheme.
