### ISSUE TITLE
freyja plot --lineages

### ISSUE THREAD

**Issue by mikal16** [andersen-lab/Freyja#186]
Hey there,

I have been using freyja for quite a bit and it's an awesome tool, however when using freyja plot recently, I seem to be running into an odd issue. This seems to have occured after updating freyja and I've noticed that aggregate files that were generated pre-update, for which freyja plot --lineages was then run, seem to show lineages fine when plotting. However, aggregate files generated post-update, which indeed have lineage information in the aggregate file, for some reason when plotted for --lineages only show "other".

Any help with this would be really appreciated.

Thanks so much!

**Comment by joshuailevy** [comment]
Hey @mikal16, 
Sorry for the delay- I was out all of last week. That's a weird change in behavior, especially since we haven't changed that part of the codebase in quite a while. 

I assume you're working with version 1.4.7 now? 

Josh

**Comment by joshuailevy** [comment]
Stale, closing for now.
