### ISSUE TITLE
Manual install

### ISSUE THREAD

**Issue by LauraVP1994** [andersen-lab/Freyja#189]
Dear,

Is it also possible to do a manual installation of freyja? If yes, how exactly?

Kind regards
Laura

**Comment by joshuailevy** [comment]
Hi @LauraVP1994! 

Yes, if you clone the Freyja repository, and navigate via command line to the corresponding directory, you should be able to install it with `pip install -e .`. That should replace the version of Freyja you're currently using. 

Let me know if you have any further questions!

Josh

**Comment by CeliaRodrigues** [comment]
For some reason that did not work either. I ended up cloning the main repository into the environment and installing it over the conda module. That gave me the results I was looking for with the updated lineages. You can close this issue.
