### ISSUE TITLE
Custom summarised lineage demix option?

### ISSUE THREAD

**Issue by AliceMichie93** [andersen-lab/Freyja#193]
Hi Josh and Dylan!

I'm aware that there is a function to present custom summarised lineage groups on plots and dashboards (which I love by the way, thank you!). 
I was wondering if there was an existing function, or one that can be introduced, where the raw abundance values of these custom groupings can be outputted for reporting purposes (perhaps by adding it as an option in the demix function)?

Thanks so much!
Alice

**Comment by joshuailevy** [comment]
Hi Alice,
Sorry we seemed to have missed this! I've just added an option to do this within plot, using the `--writegrouped` option. It'll be part of the next release.
Josh

**Comment by AliceMichie93** [comment]
Hi Josh,
No worries at all, and thank you for including a solution in the next release! 
Thanks again!
Alice
