### ISSUE TITLE
Omicron = A ?

### ISSUE THREAD

**Issue by pmenzel** [andersen-lab/Freyja#20]
Hi,

thanks for making such an easily accessible and functional tool!

I just installed Freyja through bioconda and got for my sample this output:
```
summarized	[('Omicron', 0.6661200000004268), ('Delta', 0.3116281285838772)]
lineages	['B.1.1.529' 'AY.43.3' 'AY.1']
abundances	[0.66612    0.2799447  0.03168343]
resid	14.57234387623232
```

after running `freyja update` today, the output for the same sample is
```
summarized	[('A', 0.6699959999989149), ('Delta', 0.31067812395089456)]
lineages	['BA.1.1' 'AY.43.3' 'AY.1']
abundances	[0.669996   0.27980382 0.03087431]
resid	15.751763606543287
```

So the summary in the first line changed `Omicron` to `A`.
Is this correct and what does the `A` mean?

**Comment by joshuailevy** [comment]
Ah, thanks for pointing that out. It looks like BA.1.1 has not yet been added to the Omicron list of curated lineages for pangolin,https://cov-lineages.org/constellations.html, or to the curated lineage dataset that's part of outbreak.info ([this](https://github.com/outbreak-info/outbreak.info/blob/master/web/src/assets/genomics/curated_lineages.json)) --- which is where I pull that info from. 

The "A" is an artifact of a programming choice made long before we were this far into the lineage alphabet, now rearing its head. I'll fix that asap. It should technically read "other" given that BA.1.1 has not yet been added to the omicron list, and will likely output Omicron once the list is updated. Sorry about that, I'd intended to get that patched by now but haven't yet managed to get that in place. Should hopefully have this, as well as the rest of the new release out tomorrow. :)

**Comment by joshuailevy** [comment]
The lineage assignments should be correct though. We're just in a brief period where the lineages available in pangolin/usher is slightly different from those that have been assigned a constellation/WHO lineage.

**Comment by joshuailevy** [comment]
I've closed this issue since it's happening upstream of freyja (GISAID still doesn't have any BA.1.1 sequences, and hence neither does outbreak.info). Should be fixed as soon as GISAID is updated.

**Comment by joshuailevy** [comment]
Metadata has been updated, in case folks are paying attention to this!

**Comment by pmenzel** [comment]
Thanks, it now says `Omicron` instead of `A`.

**Comment by joshuailevy** [comment]
Great! Thanks for confirming.
