### ISSUE TITLE
Is there a risk that freyja recover the wrong XDD relative lineage abundances?

### ISSUE THREAD

**Issue by Fuyulinn** [andersen-lab/Freyja#205]
It can be known from the cov-lineages that XDD is recombination composed by EG.5.1.1 and JN.1. And compared with EG.5.1.1 and JN.1, XDD dons't have special mutation site. So, I have a question: how does freyja recover relative lineage abundances from mixed SARS-CoV-2 samples? Is there a risk that freyja will identify EG.5.1.1 or JN.1 as XDD, or vice versa?
Hope get a question to this question, thanks!

**Comment by joshuailevy** [comment]
Hey @Fuyulinn! 

Freyja leverages the unique combination of mutations (aka the lineage "barcode") that define that lineage. Even if there are no novel mutations in XDD, it is a unique recombinant of the two. As such, the SNV frequencies of the mutations in the sample for the set of mutations in XDD will be increased for the specific mutations present in the recombinant, while missing some mutations present in its parents. While there is the potential for false detections of parents, in general Freyja is able to leverage the information stored across mutation sites, and pretty good at this sort of thing provided good quality data :) 

Josh

**Comment by Fuyulinn** [comment]
Many thanks for your replying！
