### ISSUE TITLE
freyja demix error citing insufficient sequencing depth 

### ISSUE THREAD

**Issue by michellescribner** [andersen-lab/Freyja#208]
Hi there! I've recently come across a sample that is failing at freyja demix and I'm not entirely sure why. I'm seeing an error message of `Solver error encountered, most likely due to insufficient sequencing depth.` , but the sample coverage is actually reasonably high (2296.98, though fairly inconsistent, as shown below).

Other samples in the same run have much lower coverage, but still succeeded. Is this expected behavior for a sample with high but inconsistent coverage? Happy to provide any other details that might be hepful!

![image](https://github.com/andersen-lab/Freyja/assets/56173868/d484a941-c234-42ba-9775-5912f6f922fe)

![image](https://github.com/andersen-lab/Freyja/assets/56173868/1b2c4488-f382-4b92-a32b-1e78e5b56e20)

freyja version: 1.4.8
freyja update version: 2024-02-06

**Comment by joshuailevy** [comment]
Hey @michellescribner! 

These solver errors can be a bit tricky to sort out at times, but it looks like the issue in your case is that even though you do have pretty good overall coverage, the coverage of the spike is only ok. A good option in this case is to try using the `--depthcutoff` parameter, which will group lineages that are indistinguishable given the available sequencing, often causing solver issues (that error message is supposed to mention this- i've just added it). It will also return a yml file that includes the lineages that have been grouped. If you set `--depthcutoff` to 1, does the solver still not converge? 

Josh

**Comment by joshuailevy** [comment]
Great to hear it @michellescribner! I'll go ahead and close this issue then :)
