### ISSUE TITLE
Some problem about the UshER barcodes output

### ISSUE THREAD

**Issue by Bin-Ma** [andersen-lab/Freyja#210]
Hi @tomkinsc,

I have some questions about the UshER barcodes output in "https://github.com/andersen-lab/Freyja/tree/main/freyja/data". 

1.  Is this file generated from UshER's VCF files in "http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/"?
2. Is there any way or script to convert the VCF format to CSV format?

Looking forward to your reply!

Bin

**Comment by joshuailevy** [comment]
Hi!

1. Yes it is. 
2. It should already be in CSV format: https://github.com/andersen-lab/Freyja/blob/main/freyja/data/usher_barcodes.csv

Best, 
Josh
