### ISSUE TITLE
Improve documentation with default values used

### ISSUE THREAD

**Issue by tavareshugo** [andersen-lab/Freyja#211]
First of all, thank you very much for developing such a useful package for the community!

I wanted to suggest adding the default values for different options to the help page of each sub-command. 
For example, when running `freyja demix --help` we don't get information about the default values for options such as `--eps`, `--covcut`, `--depthcutoff`, etc. 
I inferred it from looking at the source code, but it would perhaps be more user-friendly if this was directly available from the help.

**Comment by joshuailevy** [comment]
Hi @tavareshugo! 

Thanks for the suggestion. That's actually a super easy fix (just requires specifying in option in our click-based CLI), we'll get that incorporated in soon! 

Josh
