### ISSUE TITLE
Random seed for freyja boot for consistent results

### ISSUE THREAD

**Issue by ktmeaton** [andersen-lab/Freyja#229]
**Is your feature request related to a problem? Please describe.**
I'm doing some testing and validation on `freyja boot`, and would love a way to control the randomness, so that I can get the exact same results each run.

**Describe the solution you'd like**
Would it be possible to add a seed parameter to the CLI for `freyja boot`, something like `--seed 123456`? And then perhaps that seed could be passed along to `perform_bootstrap` and `bootstrap_parallel` with `numpy.random.seed`?

**Describe alternatives you've considered**
I'm mostly working with the freyja [Docker images](https://quay.io/repository/biocontainers/freyja) and conda, so I'm trying to avoid doing any dependency modification myself. But if this feature isn't really helpful for anyone else, I can probably figure out another way!

**Additional context**
I'm working with `freyja` in a Nextflow pipeline, and have created some test datasets as "controls" so that users can validate and compare their observed results vs. the expected results. For `freyja demix`, this works great, because the results never change on subsequent runs. But the lineages and abundaces of `freyja boot` change slightly each time without a seed for `numpy`.

Thanks!
Katherine

**Comment by mariaelf97** [comment]
Thanks for your suggestion, we will add this feature soon.
