### ISSUE TITLE
freyja boot command has error message "Error: No such command 'boot'."

### ISSUE THREAD

**Issue by mokrobial** [andersen-lab/Freyja#23]
Steps to reproduce:
1. process files with freyja 
2. use update command
**$ freyja update**
3. use specified syntax:
**$ freyja boot [variants-file] [depth-file] --nt [number-of-cpus] --nb [number-of-bootstraps] --output_basename [base-name] with freyja generated files**

Result:
Usage: freyja [OPTIONS] COMMAND [ARGS]...
Try 'freyja --help' for help.
Error: No such command 'boot'.

Environment:
* conda installation & environment
* macOS Monterey
* bash shell 

Maybe this function isn't ready for primetime? Either way, great suite of tools! What a gem!

**Comment by joshuailevy** [comment]
Hi @mokrobial! 

Thanks for letting me know. Do you know which version of freyja you're using? The ```boot``` command is only available in the most recent version (v1.3). I've found that it sometimes takes a little while before the most recent version shows up in conda's list of available versions (when pulling from the command line-- it seems to show up [here](https://anaconda.org/bioconda/freyja) immediately). 

Josh

**Comment by joshuailevy** [comment]
Closing since I think this was just due to a lag in bioconda updates.
