### ISSUE TITLE
Freyja plot key is hard to read

### ISSUE THREAD

**Issue by nicolegobo** [andersen-lab/Freyja#234]
Thank you for making Freyja! It is a great tool and the way you are managing the lineages/curated lineages is very helpful! I was wondering, would it be possible to make the text in the key bigger? It can be hard to read.

Also, the sample names are getting cut off. Would it be possible to trim off the text "_freyja_variants.tsv" that might make it easier to read the sample names.  Here is an example below:

![lineage_plot](https://github.com/andersen-lab/Freyja/assets/54408219/f69912e4-26ce-484b-975c-52d6147b59ce)

**Comment by joshuailevy** [comment]
Hey @nicolegobo! 

Thanks for bringing this up- we can throw in a custom filename extension/trimming option in plot that should handle this. We'll get it into the next release for sure. 

Josh

**Comment by nicolegobo** [comment]
Hello @joshuailevy,
Thank you so much! I can't wait! 

Would it be possible to try to also increase font size in the key/legend?

Nicole

**Comment by joshuailevy** [comment]
For sure. Might not happen for a week or two, but we'll get there soon!
