### ISSUE TITLE
Breaking out novel variants given BA.2.86 evolution 

### ISSUE THREAD

**Issue by andrew-rothstein** [andersen-lab/Freyja#241]
Given the updates from [WHO over the past months on VOC and VUM](https://www.who.int/activities/tracking-SARS-CoV-2-variants), is there a way freyja can break out the [curated_lineages.json](https://github.com/andersen-lab/Freyja/blob/main/freyja/data/curated_lineages.json) file to express this granularity?  Mostly considering JN.1 and KP lineages as of recent.  

Recognizing that this could be done from the user side but we super appreciated all the curation from the Freyja team! If not possible or there are specific reasons for keeping the groups, that would be helpful in case we want to scope a custom approach.  

Thank you!

**Comment by joshuailevy** [comment]
Hey @andrew-rothstein , 

That was previously updated via our outbreak.info side, but the person who was keeping that in sync with WHO/CDC/etc. guidelines left a few months back - I'll make sure that gets back in line with WHO designations and is updated regularly. 

Josh

**Comment by joshuailevy** [comment]
Should be good to go - matches the WHO spec.

**Comment by andrew-rothstein** [comment]
Amazing! Thank you @joshuailevy for the quick turn - super appreciated!
