### ISSUE TITLE
pyarrow missing from conda environment in v1.5.1

### ISSUE THREAD

**Issue by ktmeaton** [andersen-lab/Freyja#244]
**Describe the bug**
Hi Freyja team! Really excited about the `v1.5.1` release, and I've started testing the latest datasets that are provided in feather format. When running in `conda`, I get the following error:

`ImportError: Missing optional dependency 'pyarrow'.  Use pip or conda to install pyarrow.`

I wonder if the bioconda recipe needs `pyarrow` in it's dependencies? https://github.com/bioconda/bioconda-recipes/blob/6627a6c8b9c760ed52d19151452631a296573df3/recipes/freyja/meta.yaml

**To Reproduce**

```bash
micromamba create --yes -n freyja-1.5.1 bioconda::freyja=1.5.1
conda activate freyja-1.5.1
freyja demix --barcodes usher_barcodes06_21_2024-00-49.feather <VARIANTS> <DEPTHS>
```

**Comment by joshuailevy** [comment]
Thanks @ktmeaton! Good catch - seems that new dependency didn't quite make it to bioconda-recipes. I've just made a PR to take care of this here: https://github.com/bioconda/bioconda-recipes/pull/48788

Josh

**Comment by ktmeaton** [comment]
Thank you so much! I just tested the new environment and it works perfect for the new feather datasets. Thank you!

**Comment by joshuailevy** [comment]
No problem! Glad that's sorted. Thanks for your help!
