### ISSUE TITLE
SARS-CoV-2 barcodes update 2024-08

### ISSUE THREAD

**Issue by ktmeaton** [andersen-lab/Freyja#247]
Hi Freyja Team!

I was wondering if a SARS-CoV-2 barcode update might be coming soon? It's been about a month since the [feather barcodes](https://github.com/andersen-lab/Freyja/blob/main/freyja/data/usher_barcodes.feather) updated, and the new [Pango v1.29](https://github.com/cov-lineages/pangolin-data/releases/tag/v1.29) lineages were released earlier this week. Is the automatic updater still waiting for a new UShER tree from UCSC, or is there a different issue?

Thanks,
Katherine

**Comment by ktmeaton** [comment]
Thank you for the quick fix, I see the latest dataset has appeared!

**Comment by joshuailevy** [comment]
No problem, thanks for letting us know!
