### ISSUE TITLE
Freyja issue

### ISSUE THREAD

**Issue by Ashita2619** [andersen-lab/Freyja#250]
Good Morning Freyja Team,

I am using Freyja tool for the analysis of wastewater samples.
I am making use of nextflow to run all the commands (variants, demix, aggregate, and plot).
Current version of Freyja I'm using - 1.5.1
I recently updated Freyja-data as well.

I am facing two issues:
1. The Variants are not getting mapped correctly before I updated Freyja-data it was working fine because of which the .final file and aggregated tsv file seems to have a slightly strange format. The screenshot attached below:

Before Freyja-data update:
![image](https://github.com/user-attachments/assets/750536b9-7c27-49c0-ab6c-15bbc1c03e8f)

After Freyja-data update:
![image](https://github.com/user-attachments/assets/8f999cc2-5857-4c65-8ce7-329902fe8358)
![image](https://github.com/user-attachments/assets/c8bb0235-ff5b-4649-9c65-7ccec4a8ce61)

2. Secondly I am getting np.float64 error which is as follows:
 Traceback (most recent call last):\n'
b'    File "/home/ssh_user/mambaforge/envs/WasteWater/bin/freyja", line 10, in <module>\n'
b'      sys.exit(cli())\n'
b'    File "/home/ssh_user/mambaforge/envs/WasteWater/lib/python3.10/site-packages/click/core.py", line 1157, in __call__\n'
b'      return self.main(*args, **kwargs)\n'
b'    File "/home/ssh_user/mambaforge/envs/WasteWater/lib/python3.10/site-packages/click/core.py", line 1078, in main\n'
b'      rv = self.invoke(ctx)\n'
b'    File "/home/ssh_user/mambaforge/envs/WasteWater/lib/python3.10/site-packages/click/core.py", line 1688, in invoke\n'
b'      return _process_result(sub_ctx.command.invoke(sub_ctx))\n'
b'    File "/home/ssh_user/mambaforge/envs/WasteWater/lib/python3.10/site-packages/click/core.py", line 1434, in invoke\n'
b'      return ctx.invoke(self.callback, **ctx.params)\n'
b'    File "/home/ssh_user/mambaforge/envs/WasteWater/lib/python3.10/site-packages/click/core.py", line 783, in invoke\n'
b'      return __callback(*args, **kwargs)\n'
b'    File "/home/ssh_user/mambaforge/envs/WasteWater/lib/python3.10/site-packages/freyja/_cli.py", line 642, in plot\n'
b'      makePlot_simple(agg_df, lineages, output, config, lineage_info,\n'
b'    File "/home/ssh_user/mambaforge/envs/WasteWater/lib/python3.10/site-packages/freyja/utils.py", line 400, in makePlot_simple\n'
b'      agg_df = prepSummaryDict(agg_df)\n'
b'    File "/home/ssh_user/mambaforge/envs/WasteWater/lib/python3.10/site-packages/freyja/utils.py", line 357, in prepSummaryDict\n'
b'      .apply(lambda x:\n'
b'    File "/home/ssh_user/mambaforge/envs/WasteWater/lib/python3.10/site-packages/pandas/core/series.py", line 4924, in apply\n'
b'      ).apply()\n'
b'    File "/home/ssh_user/mambaforge/envs/WasteWater/lib/python3.10/site-packages/pandas/core/apply.py", line 1427, in apply\n'
b'      return self.apply_standard()\n'
b'    File "/home/ssh_user/mambaforge/envs/WasteWater/lib/python3.10/site-packages/pandas/core/apply.py", line 1507, in apply_standard\n'
b'      mapped = obj._map_values(\n'
b'    File "/home/ssh_user/mambaforge/envs/WasteWater/lib/python3.10/site-packages/pandas/core/base.py", line 921, in _map_values\n'
b'      return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)\n'
b'    File "/home/ssh_user/mambaforge/envs/WasteWater/lib/python3.10/site-packages/pandas/core/algorithms.py", line 1743, in map_array\n'
b'      return lib.map_infer(values, mapper, convert=convert)\n'
b'    File "lib.pyx", line 2972, in pandas._libs.lib.map_infer\n'
b'    File "/home/ssh_user/mambaforge/envs/WasteWater/lib/python3.10/site-packages/freyja/utils.py", line 358, in <lambda>\n'
b'      {k: float(v)\n'
b'    File "/home/ssh_user/mambaforge/envs/WasteWater/lib/python3.10/site-packages/freyja/utils.py", line 358, in <dictcomp>\n'
b'      {k: float(v)\n'
b"  ValueError: could not convert string to float: 'np.float640.9961165923102743'\n"

Can you please look into it.

Thank you 
~ Ashita

**Comment by dylanpilz** [comment]
Hey good morning,

Thanks for providing these screenshots. As you pointed out, Freyja is writing the raw `np.float64` value to the `summarized` column, which `freyja aggregate` does not expect so it throws an error. I'll push a fix to this soon!

**Comment by Ashita2619** [comment]
Thanks for the push the np.float64 issue got fixed! 

 As you can see in this plot, only "Other" variants are showing up in all samples. 
![image](https://github.com/user-attachments/assets/09d2c2d5-4aed-4b56-9bc0-cb18709adedb)

Is there a reason why it is happening?

Thank You,
Ashita

**Comment by dylanpilz** [comment]
Sure thing, glad it's working on your end!

It seems you might have an outdated curated lineages set.  By default, `freyja plot` will group the lineages in the lineages row into groups defined in `freyja/data/curated_lineages.json`. You could also use the `--lineages` flag to plot the raw lineage abundances without any grouping.

You mentioned getting the most recent version of Freyja-data, but could you run `freyja update` just to be sure?

**Comment by joshuailevy** [comment]
Thanks @dylanpilz! 

Also @Ashita2619, if you are using specific barcodes from freyja-data, you'll need to make sure you have similarly up to data lineage hierarchy and metadata files (from the associated folders within freyja-data), which can be supplied using the `--lineageyml` and `--meta` commands in `demix`. Alternatively, you can just take the most recent version of those files using `freyja update` as @dylanpilz mentioned!

**Comment by Ashita2619** [comment]
Thanks for the replies it seems to work fine after the Freyja update and using --lineages flag.
