### ISSUE TITLE
Release new version for bug fix

### ISSUE THREAD

**Issue by arianna-smith** [andersen-lab/Freyja#254]
Commit https://github.com/andersen-lab/Freyja/commit/2eb2afd2b1ff9d87d2e478d57aa3328bfbe3f616 fixed a bug where the abundance float in the `summarized` column of the `demix` file was being output as `np.float64({abundance})`. However, without a new version release, we can't use the corrected code and therefore have the `np.float` string in our demix file outputs, which causes problems with our downstream analyses. Thanks!

**Comment by joshuailevy** [comment]
No problem - just added one additional update feature, will drop the new release as soon as all of the tests complete!

**Comment by joshuailevy** [comment]
Should be good to go - the release should be picked up by bioconda shortly!

**Comment by laura-bankers** [comment]
Hey @joshuailevy - any idea what the timeline is for the conda recipe to get update, or what their turnaround time tends to be?

**Comment by joshuailevy** [comment]
Hey @laura-bankers! Their turnaround time is pretty variable unfortunately (anywhere from a few hours to a few days in my experience), and there appears to be something weird going on with azure servers they're using for testing... I'll try to move things forward with them again!

**Comment by laura-bankers** [comment]
Thanks @joshuailevy, I really appreciate it!
