### ISSUE TITLE
[BUG] Recombinants like XEC not being reported/detected

### ISSUE THREAD

**Issue by elserj** [andersen-lab/Freyja#256]
**Describe the bug**
Even though the recombinant variant XEC has been shown to be a large abundance, Freyja is not reporting any detection of it for us.

**To Reproduce**
1. Run `freyja update`
2. Run `freyja variants...`
3. Run `freyja demix... `

**Expected behavior**
It's been several weeks since XEC was reported to be a Variant of Concern (VOC), but we are still not seeing Freyja report it in our wastewater samples.

**Additional info (please include the following information, if applicable):**
 - Freyja version 1.4.5
 - Barcode file version 11_12_2024-01-52

**Additional context**
We've been using Freyja for analyzing our wastewater samples for quite some time, and I know it is has reported on recombinants like XBB in the past, but I would have expected to see some XEC in our samples over the last few weeks, but we have not. I guess it is possible it just hasn't made it to our location yet, but that seems unlikely. 

I think it is more likely that there is an issue differentiating XEC from KP.3.3, as that is what we are showing as our second dominant variant. The dominant variant we see is KP.3.1.1. We see a bit of KS.1.1 (the other variant recombinant with KP.3.3 to make XEC), but it is low on the list.

It is possible it is because we are running an older version of Freyja, but I wouldn't think that would cause a difference in variant detection, as the barcodes are up-to-date.

Please let me know if I can provide any further information.

**Comment by joshuailevy** [comment]
Hey @elserj!

I think you're probably not looking at fully updated barcodes actually - the old csv barcodes got too big for continued updates, so we changed data storage formats. If you're dead set on using version 1.4.5, that is should be ok, but you'll have to pull barcodes via git LFS here: https://github.com/andersen-lab/Freyja-data/blob/main/usher_barcodes.csv
 
The easier approach is to just update to the current version, which automatically pulls the compressed barcodes. 

Josh

**Comment by joshuailevy** [comment]
@elserj did that end up working for you? If not I'm happy to look further into this!

**Comment by elserj** [comment]
Apologies, I went on a trip and didn't fully test it out before I left.

However, I've updated it to 1.5.2, but now all of my demix output files are showing no variants, like this:

> summarized      []
> lineages
> abundances
> resid   -1
> coverage        52.6669564926596

I'm still trying to figure out why, it is the same sorted bam file as input that was working fine with the older version. My current guess is that the method to download the barcodes has changed and is now failing because of the proxy server our compute nodes are behind.

Unless some input parameter has changed? I was using the exact same command I was before.

**Comment by joshuailevy** [comment]
No worries - that's a bit strange, looks like the solver isn't converging for some reason. The `freyja update` command should still be the same though. 

Perhaps try using the `--depthcutoff` parameter (set it to 10 or so) to see if it's just failing to distinguish between a handful of lineages that aren't distinguishable given the available coverage? Happy to take a look at the variants/depths files if you're still stuck.

**Comment by elserj** [comment]
Hmm, you appear to be right that it's the solver, but I don't understand why. This sample worked fine with Ver 1.4.5:
```
(freyja) [elserj@jackson test]$ freyja update
Getting outbreak data
Downloading barcodes
(freyja) [elserj@jackson test]$ freyja demix --version
Barcode version:
11_19_2024-02-01

(freyja) [elserj@jackson test]$ freyja variants test_file.sorted.bam --variants test_file.variants --depths test_file.depths --ref ../data/ref/covid19.fasta 
samtools mpileup -aa -A -d 600000 -Q 20 -q 0 -B -f ../data/ref/covid19.fasta test_file.sorted.bam | tee >(cut -f1-4 > test_file.depths) | ivar variants -p test_file.variants -q 20 -t 0.0 -r ../data/ref/covid19.fasta
[mpileup] 1 samples in 1 input files
(freyja) [elserj@jackson test]$ freyja demix test_file.variants.tsv test_file.depths --output test_file.output --depthcutoff 10
collapsed lineages saved to test_file_collapsed_lineages.yml
building mix/depth matrices
demixing
Solver error encountered, most likely due to insufficient sequencing depth.Try running with --depthcutoff.
Error: Demixing step failed. Returning empty data output
```

I even tried upping the depthcutoff to 90, and it still failed to solve.

I normally run this in a snakemake pipeline I wrote for all of the samples to be done at once, but all of them failed where it worked fine with the older version. Also, apparently the errors aren't logged in the snakemake logs, so I need to figure that out as well.

I am attaching the variants and depths files. I did check and there is no diff between these and the ones from the older version.
[test_file.depths.txt](https://github.com/user-attachments/files/17820541/test_file.depths.txt)
[test_file.variants.tsv.txt](https://github.com/user-attachments/files/17820543/test_file.variants.tsv.txt)

This is the output for the same sample file from ver 1.4.5:
```
summarized      [('KP.3.1.1* (KP.3.1.1.X)', 0.5535710000001199), ('KP.3* (KP.3.X)', 0.24642899999964762), ('KP.2* (KP.2.X)', 0.19999999999892856)]
lineages        KP.3.1.1 KP.3.1 KP.2.3 KP.3.3 KP.2.10
abundances      0.55357100 0.18760550 0.15652170 0.05882350 0.04347830
resid   2.712978143238214
coverage        52.6669564926596
```

**Comment by elserj** [comment]
Sorry, adding a bit more here:

I also had my snakemake pipeline automatically rerun samples in the past that would fail due to insufficient depth errors, but it appears to no longer exit with a return code other than 0, so snakemake no longer realizes there was an issue. I had it set up where if the demix step failed, it would try again based on the attempt number with `[0,1,5,10,20,50,75]` as an array for the depthcutoff parameter.

In debugging why the errors weren't getting logged, it was because I was using `2> {log}`, which only redirects stderr. Changing it to `&> {log}` now shows the solver error message, but it appears be written to stdout instead of stderr, and the exit return code is 0, even though it failed.

**Comment by joshuailevy** [comment]
Just ran the file (without `--depthcutoff`) and it seems to work fine. I'm on the same barcode version as you... I figure you're running this on a linux box? And `freyja --version` returns 1.5.2? 
 
```
        test_file.variants.tsv
summarized      [('KP.3.1.1* (KP.3.1.1.X)', 0.5535709951584062), ('KP.3* (KP.3.X)', 0.24642898978020528), ('KP.2* (KP.2.X)', 0.17826085103903405), ('BA.2.86* (BA.2.86.X)', 0.02173914688744326)]
lineages        MC.10 KP.3.1 MC.15 KP.3.1.1 KP.2.3.9 KP.2.3 KP.3.3 KP.1.1.5 KP.2.10
abundances      0.20000000 0.18760550 0.17678550 0.17678550 0.07826085 0.07826085 0.05882349 0.02173915 0.02173915
resid   2.787466110109875
coverage        52.6669564926596
```

**Comment by joshuailevy** [comment]
No worries - glad it's working. 

And we should be able to add an error code back into the exception. @dylanpilz what do you think? Should just be a one liner?
