### ISSUE TITLE
Only SNPs but no INDELs in `usher_barcodes.csv`

### ISSUE THREAD

**Issue by SteamedFish6** [andersen-lab/Freyja#258]
Excuse me, could you please tell me why `usher_barcodes.csv` only contains SNPs but no INDELs? The INDEL type mutation sites can be detected by variant calling from BAM files, but these mutation sites seem not to be taken part in demixing.
The barcode was built from `protobuf tree`, I wonder if `protobuf tree` includes SNPs only, or, whether INDELs are necessary for demixing or not?

**Comment by joshuailevy** [comment]
Hi - you're correct, the UShER tree (which is used for most consensus sequence lineage assignment, and also to build the Freyja barcodes) only contains SNPs, so we don't have that information for demixing unfortunately. This comes down to some fundamental issues in phylogenetic inference - which has nice models for SNP rates, but indels are not explicitly described.

**Comment by SteamedFish6** [comment]
Thanks, learned a lot.

**Comment by joshuailevy** [comment]
No problem!
