### ISSUE TITLE
Deprecated warning messages

### ISSUE THREAD

**Issue by AnehEf** [andersen-lab/Freyja#39]
Hi wonderful Freyja's team, 

When I update the database (freyja update), I get the warnings below. 
`
/anaconda3/envs/freyja/lib/python3.10/site-packages/freyja/convert_paths2barcodes.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_barcodes = df_barcodes.append(cladeSeries)
`

I also get this error, which I don't know if I should worry about:
`
/anaconda3/envs/freyja/lib/python3.10/site-packages/freyja/convert_paths2barcodes.py:41: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  temp[mt] = df_barcodes[c]
`
 
When using the demix function, I get the warning: 
`
/anaconda3/envs/SARSCoV2/lib/python3.8/site-packages/freyja/sample_deconv.py:42: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  mix = df.loc[keptInds, 'ALT_FREQ'].astype(float)
`

 Thanks
 Adelaide

**Comment by joshuailevy** [comment]
Hi Adelaide, thanks for bringing this up! No need to worry about those for now, as they shouldn't impact the functionality of the code. I'm planning to fix those up for the upcoming release :) 
Best,
Josh

**Comment by AnehEf** [comment]
Thanks

**Comment by joshuailevy** [comment]
incorporated into most recent push, will enter into new release in the next few days
