### ISSUE TITLE
Suggestions for including deletion or insertion mutations into mutation barcode file

### ISSUE THREAD

**Issue by JHarrisonEcoEvo** [andersen-lab/Freyja#42]
Hi there! Thanks for a nice tool. 

It appears that the USHER tool does not support indel mutations ([see the thread at this link](https://github.com/yatisht/usher/issues/179)). Is there a way to feed in indel data to Freyja in a custom barcode file? 

Thanks!

**Comment by joshuailevy** [comment]
Hi @JHarrisonEcoEvo! 

Glad you're finding it useful. Yep, UShER (currently) doesn't support indels, but I believe adding them to their tree is in their future plans. 

We're not currently incorporating this functionality (it works with a handful of changes, and was part of early versions of my code) but for many of the same reasons mentioned in that post -- as well as the lack of a comparable source of lineage-specific lists of indels (unless you know of one?) -- adding of indels is part of our future, though not immediate future, plans.

By the way, I saw that you and the biobot crew dropped a huge wastewater sequencing dataset on NCBI (per the CDC SPHERES channel). Looks like a great resource, definitely going to check it out! 

Josh

**Comment by JHarrisonEcoEvo** [comment]
Thanks for the quick response and info! 

In case you haven't seen it the constellation list at cov-lineages has some deletion info for different lineages ([link)](https://cov-lineages.org/constellations.html). Maybe something of use to you over there, for future iterations of Freyja.

Glad our data dump is of interest. If you get a chance to check out the data definitely reach out and let us know any cool findings! 

Thanks again, jh
