### ISSUE TITLE
Filter out recombinant lineages?

### ISSUE THREAD

**Issue by SVN-PhD** [andersen-lab/Freyja#43]
Would it be possible to filter out recombinant lineages when using `--lineages`? Especially with some of these new recombinants as a mix of various Omicron subvariants and some Delta lineages, the data can be a bit messy. Thanks!

![Screenshot from 2022-04-07 10-35-34](https://user-images.githubusercontent.com/15314705/162226310-5c13d277-4d8f-4c2c-bee9-85a5b939ecad.png)

**Comment by joshuailevy** [comment]
Hi! 
This can be done by first running ```freyja update --outdir your-dir``` and then modifying the ```usher_barcodes.csv``` file as you see fit (e.g. removing all rows beginning with an X). This barcode library can then be fed directly into ```freyja demix ``` via the --barcodes argument.

Josh

**Comment by joshuailevy** [comment]
Closing this since it's already possible using the existing codebase.
