### ISSUE TITLE
Add version

### ISSUE THREAD

**Issue by erinyoung** [andersen-lab/Freyja#44]
It would be helpful to me if there was a `-v` or `-V` or `--version` or even `freyja version` for an easy way to see if I'm current.

**Comment by joshuailevy** [comment]
That's a good point. One easy way around this is to run ```conda list``` in your conda environment, which should tell you the conda version. I'll add this into the next release :)

**Comment by erinyoung** [comment]
Thank you!

**Comment by joshuailevy** [comment]
Has been added to github repo, will be part of version 1.3.5.
