### ISSUE TITLE
KeyError over many samples when using Freyja demix

### ISSUE THREAD

**Issue by evantroendle** [andersen-lab/Freyja#50]
Hello, I have been using Freyja for a research project and it has been very useful, interesting, and helpful, so thank you!

Regarding this issue:

I am batch processing 40252 *.bam files, but for some reason only 15364 of them have 'gotten through' the freyja demix step. All of the failures come from similar KeyErrors, and the mean alignment properties are below (showing most alignments are decent):
n_reads           107792
n_mapped          102044
percent_mapped        93.65

Example of a frequent error message:

freyja demix /media/evan/DATA2/freyja/NIRE-00304f_S45_freyja_variants.tsv /media/evan/DATA2/freyja/NIRE-00304f_S45_freyja_depth.tsv --output /media/evan/DATA2/freyja/NIRE-00304f_S45_freyja_demix.tsv
/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/freyja/sample_deconv.py:42: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  mix = df.loc[keptInds, 'ALT_FREQ'].astype(float)
building mix/depth matrices
Traceback (most recent call last):
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)A
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 2131, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 2140, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 22356

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/evan/anaconda3/envs/freyja-env/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/freyja/_cli.py", line 48, in demix
    mix, depths_ = build_mix_and_depth_arrays(variants, depths, muts)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/freyja/sample_deconv.py", line 44, in build_mix_and_depth_arrays
b"    depths = pd.Series({kI: df_depth.loc[int(re.findall(r'\\d+', kI)[0]), 3]\n"
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/freyja/sample_deconv.py", line 44, in <dictcomp>
b"    depths = pd.Series({kI: df_depth.loc[int(re.findall(r'\\d+', kI)[0]), 3]\n"
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/pandas/core/indexing.py", line 960, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/pandas/core/frame.py", line 3622, in _get_value
    row = self.index.get_loc(index)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 22356\n

The variants and depth tsvs are attached (as txt)
[NIRE-00304f_S45_freyja_depth.tsv.txt](https://github.com/andersen-lab/Freyja/files/8495910/NIRE-00304f_S45_freyja_depth.tsv.txt)
[NIRE-00304f_S45_freyja_variants.tsv.txt](https://github.com/andersen-lab/Freyja/files/8495911/NIRE-00304f_S45_freyja_variants.tsv.txt)
 in case this helps.

I will leave my conda list in case for replication or to otherwise spot a versioning issue:
 packages in environment at /home/evan/anaconda3/envs/freyja-env:

 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h7f8727e_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
attrs                     21.4.0             pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.10.0             pyh06a4308_0  
blas                      1.0                    openblas  
bleach                    4.1.0              pyhd3eb1b0_0  
boost-cpp                 1.74.0               h6cacc03_7    conda-forge
bottleneck                1.3.4            py39hce1f21e_0  
bowtie2                   2.4.5            py39hd2f7db1_2    bioconda
brotli                    1.0.9                he6710b0_2  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.18.1               h7f8727e_0  
ca-certificates           2022.3.29            h06a4308_0  
certifi                   2021.10.8        py39h06a4308_2  
cffi                      1.15.0           py39hd667e15_1  
click                     8.0.4            py39h06a4308_0  
colorama                  0.4.4              pyhd3eb1b0_0  
cvxpy                     1.2.0            py39hf3d152e_0    conda-forge
cvxpy-base                1.2.0            py39h1832856_0    conda-forge
cycler                    0.11.0             pyhd3eb1b0_0  
dbus                      1.13.6               h5008d03_3    conda-forge
debugpy                   1.5.1            py39h295c915_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
ecos                      2.0.7.post1      py39h6323ea4_0  
entrypoints               0.3              py39h06a4308_0  
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.4.8                h27087fc_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hd3eb1b0_0  
font-ttf-inconsolata      2.001                hcb22688_0  
font-ttf-source-code-pro  2.030                hd3eb1b0_0  
font-ttf-ubuntu           0.83                 h8b1ccd4_0  
fontconfig                2.13.96              h8e229c2_2    conda-forge
fonts-anaconda            1                    h8fa9717_0  
fonts-conda-ecosystem     1                    hd3eb1b0_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.11.0               h70c0345_0  
**freyja                    1.3.4              pyhdfd78af_0    bioconda**
gettext                   0.21.0               hf68c758_0  
giflib                    5.2.1                h7b6447c_0  
gst-plugins-base          1.20.1               hcf0ee16_1    conda-forge
gstreamer                 1.20.1               hd4edc92_1    conda-forge
hisat2                    2.1.0                h5005445_0    biobuilds
htslib                    1.14                 h9753748_2    bioconda
icu                       69.1                 h9c3ff4c_0    conda-forge
importlib-metadata        4.11.3           py39h06a4308_0  
importlib_metadata        4.11.3               hd3eb1b0_0  
ipykernel                 6.9.1            py39h06a4308_0  
ipython                   8.2.0            py39h06a4308_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
isa-l                     2.30.0               ha770c72_4    conda-forge
ivar                      1.3.1                hecb563c_3    bioconda
jbig                      2.1                  hdba287a_0  
jedi                      0.18.1           py39h06a4308_1  
jinja2                    3.0.3              pyhd3eb1b0_0  
joblib                    1.1.0              pyhd3eb1b0_0  
jpeg                      9e                   h7f98852_0    conda-forge
jsonschema                3.2.0              pyhd3eb1b0_2  
jupyter_client            7.1.2              pyhd3eb1b0_0  
jupyter_core              4.9.2            py39h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
kiwisolver                1.3.2            py39h295c915_0  
krb5                      1.19.2               hac12032_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h295c915_0  
libblas                   3.9.0                8_openblas    conda-forge
libcbor                   0.9.0                h9c3ff4c_0    conda-forge
libclang                  13.0.1          default_hc23dcda_0    conda-forge
libcurl                   7.82.0               h0b77cf5_0  
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20210910         h7f8727e_0  
libev                     4.33                 h7f8727e_1  
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h295c915_2  
libfido2                  1.10.0               h812cca2_0    conda-forge
libgcc-ng                 11.2.0              h1d223b6_14    conda-forge
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libglib                   2.70.2               h174f98d_4    conda-forge
libgomp                   11.2.0              h1d223b6_14    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libllvm13                 13.0.1               hf817b99_2    conda-forge
libnghttp2                1.46.0               hce63b2e_0  
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.5                h27cfd23_1  
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libpq                     14.2                 hd57d9b9_0    conda-forge
libprotobuf               3.18.1               h780b84a_0    conda-forge
libsodium                 1.0.18               h7b6447c_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              11.2.0              he4da1e4_14    conda-forge
libtiff                   4.3.0                h542a066_3    conda-forge
libudev1                  249                  h7f98852_1    conda-forge
libuuid                   2.33.1               h14c3975_0    biobuilds
libvorbis                 1.3.7                h7b6447c_0  
libwebp                   1.2.2                h55f646e_0  
libwebp-base              1.2.2                h7f8727e_0  
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
lz4-c                     1.9.3                h295c915_1  
mafft                     7.490                hec16e2b_1    bioconda
markupsafe                2.0.1            py39h27cfd23_0  
matplotlib                3.5.1            py39h06a4308_1  
matplotlib-base           3.5.1            py39ha18d171_1  
matplotlib-inline         0.1.2              pyhd3eb1b0_2  
mistune                   0.8.4           py39h27cfd23_1000  
mpi                       1.0                     openmpi  
munkres                   1.1.4                      py_0  
mysql-common              8.0.28               haf5c9bc_2    conda-forge
mysql-connector-c         6.1.11               h24aacaa_2  
mysql-libs                8.0.28               h28c427c_2    conda-forge
nb_conda_kernels          2.3.1            py39h06a4308_0  
nbclient                  0.5.11             pyhd3eb1b0_0  
nbconvert                 6.4.4            py39h06a4308_0  
nbformat                  5.3.0            py39h06a4308_0  
ncurses                   6.3                  h7f8727e_2  
nest-asyncio              1.5.5            py39h06a4308_0  
nextclade                 1.11.0               h9ee0642_0    bioconda
notebook                  6.4.8            py39h06a4308_0  
nspr                      4.33                 h295c915_0  
nss                       3.74                 h0370c37_0  
numexpr                   2.8.1            py39hecfb737_0  
numpy                     1.21.5           py39h7a5d4dd_1  
numpy-base                1.21.5           py39hb8be1f0_1  
openmpi                   4.1.3                h414127c_0    conda-forge
openssh                   8.9p1                hf695f80_0    conda-forge
openssl                   1.1.1n               h7f8727e_0  
osqp                      0.6.2.post0      py39hde0f152_3    conda-forge
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.4.1            py39h295c915_1  
pandocfilters             1.5.0              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
pcre                      8.45                 h295c915_0  
perl                      5.26.2               h14c3975_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.0.1            py39h22f2fdc_0  
pip                       21.2.4           py39h06a4308_0  
prometheus_client         0.13.1             pyhd3eb1b0_0  
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
pthread-stubs             0.3                  h0ce48e5_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.11.2             pyhd3eb1b0_0  
pyparsing                 3.0.4              pyhd3eb1b0_0  
pyqt                      5.12.3           py39hf3d152e_8    conda-forge
pyqt-impl                 5.12.3           py39hde8b62d_8    conda-forge
pyqt5-sip                 4.19.18          py39he80948d_8    conda-forge
pyqtchart                 5.12             py39h0fcd23e_8    conda-forge
pyqtwebengine             5.12.1           py39h0fcd23e_8    conda-forge
pyrsistent                0.18.0           py39heee7806_0  
python                    3.9.12          h9a8a25e_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.15.1             pyhd3eb1b0_0  
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd3eb1b0_0  
pyzmq                     22.3.0           py39h295c915_2  
qdldl-python              0.1.5            py39hde0f152_2    conda-forge
qt                        5.12.9               h1304e3e_6    conda-forge
readline                  8.1.2                h7f8727e_1  
samtools                  0.1.19               h887b0a7_1    biobuilds
scipy                     1.7.3            py39h492baa0_0  
scs                       3.2.0            py39h0ec8588_0    conda-forge
seaborn                   0.11.2             pyhd3eb1b0_0  
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                61.2.0           py39h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
soupsieve                 2.3.1              pyhd3eb1b0_0  
sqlite                    3.38.2               hc218d9a_0  
stack_data                0.2.0              pyhd3eb1b0_0  
tbb                       2020.2               h4bd325d_4    conda-forge
terminado                 0.13.1           py39h06a4308_0  
testpath                  0.5.0              pyhd3eb1b0_0  
tk                        8.6.12               h27826a3_0    conda-forge
tornado                   6.1              py39h27cfd23_0  
tqdm                      4.63.0             pyhd3eb1b0_0  
traitlets                 5.1.1              pyhd3eb1b0_0  
typing-extensions         4.1.1                hd3eb1b0_0  
typing_extensions         4.1.1              pyh06a4308_0  
tzdata                    2022a                hda174b7_0  
ucsc-fatovcf              426                  h954228d_0    bioconda
usher                     0.5.3                hf1ae886_0    bioconda
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1            py39h06a4308_1  
wheel                     0.37.1             pyhd3eb1b0_0  
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h7b6447c_0  
zeromq                    4.3.4                h2531618_0  
zipp                      3.7.0              pyhd3eb1b0_0  
zlib                      1.2.11            h166bdaf_1014    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge

All the best,
Evan

**Comment by joshuailevy** [comment]
Hi Evan! 

Thanks for letting me know, I haven't seen an error like this before. It seems like something might be wrong with your depth file (sites with 0 depth aren't listed). Did you remove those rows to reduce file size? If you send a copy of the corresponding bam file I can investigate in greater detail what might be going on. 

Josh

**Comment by joshuailevy** [comment]
Also, the warning shown at the top has been sorted and the fix is part of the 1.3.5 release, which should soon be available via bioconda (has been queued for release for a couple of days now).

**Comment by evantroendle** [comment]
Hi Josh,

Apologies for the delay - Here's the .bam (as .txt) - I also sorted it using samtools before running with freyja - I'm not sure if this impacts the results in any way.
[NIRE-00304f_S45.bam.txt](https://github.com/andersen-lab/Freyja/files/8549341/NIRE-00304f_S45.bam.txt)

Best,
Evan

**Comment by joshuailevy** [comment]
Hi Evan, 

I ran the following commands, and freyja seems to have run fine (completed with no warnings or errors):

```freyja variants NIRE-00304f_S45.bam --variants test_evan.tsv --depths test_evan.depth --ref ../MN908947.3.fasta```
and
```freyja demix test_evan.tsv test_evan.depth --output test_evan.output```

Sorting the bam is a good idea, and freyja will likely throw an error if you don't :) 

Here's all of the output files
[test_evan.tsv.txt](https://github.com/andersen-lab/Freyja/files/8592365/test_evan.tsv.txt)
[test_evan.output.txt](https://github.com/andersen-lab/Freyja/files/8592366/test_evan.output.txt)
[test_evan.depth.txt](https://github.com/andersen-lab/Freyja/files/8592367/test_evan.depth.txt)

Josh

**Comment by ssorgatem** [comment]
I am running into the same issue with my samples:

Traceback (most recent call last):
  File "/zpool_1TB/lib/miniconda3/envs/xarxa_covid/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/zpool_1TB/lib/miniconda3/envs/xarxa_covid/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/zpool_1TB/lib/miniconda3/envs/xarxa_covid/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/zpool_1TB/lib/miniconda3/envs/xarxa_covid/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/zpool_1TB/lib/miniconda3/envs/xarxa_covid/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/zpool_1TB/lib/miniconda3/envs/xarxa_covid/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/zpool_1TB/lib/miniconda3/envs/xarxa_covid/lib/python3.9/site-packages/freyja/_cli.py", line 55, in demix
    mix, depths_, cov = build_mix_and_depth_arrays(variants, depths, muts,
  File "/zpool_1TB/lib/miniconda3/envs/xarxa_covid/lib/python3.9/site-packages/freyja/sample_deconv.py", line 51, in build_mix_and_depth_arrays
    depths = pd.Series({kI: df_depth.loc[int(re.findall(r'\d+', kI)[0]), 3]
  File "/zpool_1TB/lib/miniconda3/envs/xarxa_covid/lib/python3.9/site-packages/freyja/sample_deconv.py", line 51, in <dictcomp>
    depths = pd.Series({kI: df_depth.loc[int(re.findall(r'\d+', kI)[0]), 3]
  File "/zpool_1TB/lib/miniconda3/envs/xarxa_covid/lib/python3.9/site-packages/pandas/core/indexing.py", line 960, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/zpool_1TB/lib/miniconda3/envs/xarxa_covid/lib/python3.9/site-packages/pandas/core/frame.py", line 3623, in _get_value
    row = self.index.get_loc(index)
  File "/zpool_1TB/lib/miniconda3/envs/xarxa_covid/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 10124

**Comment by ssorgatem** [comment]
Here's the depths file generated: [sample.depths.txt](https://github.com/andersen-lab/Freyja/files/8715529/sample.depths.txt)

I'm trying to figure out a way to upload and link the bam file

**Comment by evantroendle** [comment]
Hi @joshuailevy,

Thank you for checking! I have corrected this issue in my version by reinstalling a new environment for freyja, for some reason my environment downgraded samtools to v0.1.19 when installing another package, which could be responsible for this error.

@ssorgatem please check your samtools version to see if having version 1.5 from bioconda helps. If not, you may upload the .bam by adding a .txt extension.

From using conda list on my renewed freyja install environment I can confirm:
samtools                  1.15                 h3843a85_0    bioconda

This allowed it to batch process >99% of samples. I will open up a new 'issue' with updated information on another issue halting the final ~100 samples out of >50k.

**Comment by ssorgatem** [comment]
It turns out my issue was (kinda) unrelated.
My problem was that my samples are aligned only against the S gene, not the whole genome, and thus the positions freyja was looking for did not exist.
I fixed it by modifying Freya's build_mix_and_depth_arrays function to fill in the missing positions with 0 coverage.

**Comment by joshuailevy** [comment]
Ok great! I'll go ahead and close this issue then!

**Comment by YuWang07** [comment]
Dear Joshua,
Thanks for developing this useful tools. I just install the version 1.3.11 and I get the following error when I am using the freyja demix function:

 File "/home/s4519890/miniconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/core/generic.py", line 5907, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'log2'
I try to converts the data type of the Series object from object to np.float64. But still not working.
I have using Evan's .bam file (Thanks for provide this file  @evantroendle) as a test and it running well with no error.  I also uploaded my bam file: https://drive.google.com/file/d/1_EUklUSMEPMxbnjz6cLSHioTfmOrIqbF/view?usp=sharing, could you please give some suggestions?

Thanks,
Yu.
