### ISSUE TITLE
Understanding Bootstraps estimates

### ISSUE THREAD

**Issue by wasimbt** [andersen-lab/Freyja#52]
Hi, 

Thanks alot for creating Frejya! It works superbly for our waste-water samples. 

I simply want to know, how we can be confident that what we are observing in samples is truly there or if we can increase the confidence score somehow (read abundance-based filtering? number/proportion of mutations recovered to confidently assign a variant?). Also could you please explain the bootstrap estimates, for example; what it means to have 95% value of a lineage? or how we can use this information in the article?

Many thanks for your answers!!

Best, 
Wasim

**Comment by joshuailevy** [comment]
Hi @wasimbt!

I'm glad that Freyja is working well for you! 

The bootstrap gives an estimate of the uncertainty in the lineage abundances estimated by Freyja. That is, if we resample the data 1000 times (with replacement, what is the range of abundance estimates that we get from Freyja?  The percentiles describe this distribution (for each lineage), where the 95% percentile is the abundance value for a given lineage such that only 5% of resampled estimates (for that lineage)are higher than that abundance. In general, a bootstrap 95% confidence interval is a good thing to report, which is the range between the 2.5% and 97.5%. For an example, see our recent [preprint](https://www.medrxiv.org/content/10.1101/2021.12.21.21268143v2), especially Extended Data Figure 6. It's also worth checking the coverage of your sequencing data (usually >60% coverage is sufficient), which can also strongly impact the quality of your results. 

Best, 
Josh

**Comment by wasimbt** [comment]
Hi Josh, 

Many thanks for your answers! It is clear to me now and I will report the 95% confidence interval abundance estimates. 

Best, 
Wasim

**Comment by joshuailevy** [comment]
Great! Going to go ahead and close this issue then. 

Josh
