### ISSUE TITLE
freyja demix output inconsistent for abundances

### ISSUE THREAD

**Issue by SESchmedes** [andersen-lab/Freyja#57]
I keep running into inconsistencies in the format for the abundances line in the freyja demix tsv output.

For example, one sample I will get the following output:
	sample1.variants.tsv
summarized	[('Delta', 0.9891650089965712)]
lineages	['AY.44' 'AY.106' 'AY.39.1' 'AY.3.1']
**abundances	[0.388514   0.26584011 0.25       0.0848109 ]**
resid	5.793999402624937
coverage	81.75099488345651

And the next sample I'll get quotes and a new line introduced breaking up the abundance line:
sample2.variants.tsv
summarized	[('Delta', 0.7286465058355318), ('Omicron', 0.14188191374126788), ('Other', 0.11252699999574227)]
lineages	['AY.39' 'AY.126' 'AY.119.2' 'BA.1' 'B.1.1.378' 'AY.117' 'AY.25' 'AY.3']
**abundances	"[0.16961648 0.169355   0.166667   0.14188191 0.112527   0.10395
 0.0726979  0.04636013]"**
resid	13.656308232291073
coverage	96.48195833193994

Does a new line get introduced after so many abundance values listed? Can this be kept to one line? I'm trying to parse the file into a final report, and I keep running into issues trying to grab all the values for each sample.

Thanks for your help,
Sarah

**Comment by joshuailevy** [comment]
Hey Sarah, 

Thanks for bringing this up. I've always just stripped out the newline characters, as shown in the ```prepLineageDict()``` function in the [utils](https://github.com/andersen-lab/Freyja/blob/main/freyja/utils.py), but I've been intending to switch to a single line format for a while now. 

Should be a quick/easy modification. I'll add this into the next release. 

Josh

**Comment by joshuailevy** [comment]
No problem! Thanks for the reminder!
