### ISSUE TITLE
BC.1 in 'confirmed only' output

### ISSUE THREAD

**Issue by jdeligt** [andersen-lab/Freyja#61]
We're running in confirmed only mode and getting BC.1 classifications while we are fairly certain this is not around in our area

**Comment by joshuailevy** [comment]
Hey @jdeligt! That's interesting. It looks like BC.1 was renamed to BE.1 actually, but it seems usher hasn't yet caught up with that change? The renaming just happened a few days ago: https://github.com/cov-lineages/pango-designation/commit/aa027b086891242968eb77628a03795811aea2e5. I'd expect (hope) that this is something that'll be sorted out in the next day or two as usher gets updated.

**Comment by jdeligt** [comment]
Thanks for that pointer, was having a hard time tracking it down.

**Comment by jdeligt** [comment]
what's weird is that if I got the right lineage comparison here: https://outbreak.info/compare-lineages?pango=BA.1&pango=BA.2&pango=B.1.1.526&pango=BA.4&pango=BA.5&gene=S&threshold=75&nthresh=1&sub=false&dark=false there is no way for us to distinguish that BC.1/BE.1 from the other lineages in the region we capture, will do some more digging to see if we can figure out what position is causing the confusion, might just be the Usher definitions that are acting up

**Comment by joshuailevy** [comment]
Yeah, was weirdly hard to sort out what was going on.  It might be helpful to look at the various mutations present in these lineages (pulled directly from the barcodes: [omicron_compare.csv](https://github.com/andersen-lab/Freyja/files/8866789/omicron_compare.csv). There seems to be a few sites that distinguish BE.1, like C1931A and G28681T, as well as others that are shared with some but not all of the omicron lineages I've included here.

**Comment by joshuailevy** [comment]
Ok, so I think a new BC.1 has been designated (https://cov-lineages.org/lineage.html?lineage=BC.1), appears to be a lineage found in Japan. Going to close this issue as I think the mystery has been solved. Feel free to reopen if not :)
