### ISSUE TITLE
Demix for low genome coverage samples

### ISSUE THREAD

**Issue by gcha31** [andersen-lab/Freyja#62]
Hi! Thanks for the great tool.

I have a few questions about the demix step. Based on my understanding, freyja incorporates a unique barcode for every lineage. In the case of low genome coverage samples that do not have amplicons covering all the characteristic mutations (missing a few mutation sites) belonging to a specific lineage, does it get assigned 'Others'?

We have several samples that have genome coverage between 10-20% and `freyja demix` assigned lineages to them. I am curious how confident these assignments can be.

Thanks!

**Comment by joshuailevy** [comment]
Hey @gcha31! 

Thanks for bringing this up. At the moment, freyja does not stop the user from analyzing low coverage samples, so some care must be taken to make sure your samples are of decent quality/coverage. In general, I wouldn't have a ton of confidence in ```freyja demix``` predictions for samples with less than 60% (10x) coverage, though where you do get that coverage is also important. 

For samples that do have a decent level of coverage, I'd recommend trying out ```freyja boot``` to get a more quantitative estimate of confidence of lineage assignments. 

Josh

**Comment by gcha31** [comment]
Thanks for your input! Yes, I will try your recommendation.

**Comment by algaraber** [comment]
Hello @joshuailevy! 

This is actually very interesting, are there any detailed guidelines?
We use Freyja regularly on wastewater samples and it works great, but when we get low genome coverage we are not sure whether to trust the abundance estimates. It is especially intriguing when a lineage that is new to the area pops up on the Freyja output!

Best,
Al
