### ISSUE TITLE
Missing lineagePaths.txt file for update command

### ISSUE THREAD

**Issue by sgsutcliffe** [andersen-lab/Freyja#67]
When I run the freyja update command I get the error:

FileNotFoundError: [Errno 2] No such file or directory: './lineagePaths.txt'. 

I see in the update.py script that
`varCmd = f"matUtils extract -i {treePath} -C lineagePaths.txt"`
There is no lineagePaths.txt, do I need to supply "lineagePaths.txt'?

**Comment by joshuailevy** [comment]
You shouldn't! It gets generated by the matUtils ```extract``` command you mention above using the UShER global phylogenetic tree (path specified as ```treePath```). 

You just have to run ```freyja update``` and this should all happen under the hood (lineagePaths.txt gets generated and then deleted during the update).

**Comment by sgsutcliffe** [comment]
I see what you mean! I was looking at the matUtils command and when I run it
`matUtils extract -i public-latest.all.masked.pb.gz  -C lineagePaths.txt`
I see it is being Killed, must be a memory issue for my computer! Sorry for the confusion.

**Comment by joshuailevy** [comment]
Ah, yes! A few other folks have run into this memory issue now that the tree is a bit bigger. Providing a little bit more memory should do the trick!

**Comment by sgsutcliffe** [comment]
Thanks for the quick reply! Great tool!
