### ISSUE TITLE
Which lineages are in my current version?

### ISSUE THREAD

**Issue by rafischulman** [andersen-lab/Freyja#68]
I ran "freyja update" within the past few days, but I am curious to know which lineages/variants are currently within my database. 

I recently ran some samples and had many variants called as "omicron", when I suspect these may instead be BA.4 or BA.5. However, I am not sure if BA.4 and/or BA.5 could be called by my current reference set.

Thanks so much!

**Comment by joshuailevy** [comment]
Hi @rafischulman! 

I'd recommend running an update using the ```--outdir [your-directory-of-choice] ```. This will output two relevant files: 1. the barcodes for all of the lineages in your database 2. a "curated lineages" json that contains all of the lineages for each constellation/VOC (search for ```"label": "Omicron"```).
