### ISSUE TITLE
Freyja dash KeyError

### ISSUE THREAD

**Issue by whottel** [andersen-lab/Freyja#69]
I am running a runinnig into an issue with "freyja dash" when I include "--eps 0.01" in the upstream "freyja demix" command.
I see the following error:

/opt/conda/envs/freyja-env/lib/python3.10/site-packages/freyja/utils.py:248: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_ab_lin = df_ab_lin.append(
/opt/conda/envs/freyja-env/lib/python3.10/site-packages/freyja/utils.py:248: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_ab_lin = df_ab_lin.append(
/opt/conda/envs/freyja-env/lib/python3.10/site-packages/freyja/utils.py:248: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_ab_lin = df_ab_lin.append(
/opt/conda/envs/freyja-env/lib/python3.10/site-packages/freyja/utils.py:248: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_ab_lin = df_ab_lin.append(
/opt/conda/envs/freyja-env/lib/python3.10/site-packages/freyja/utils.py:248: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_ab_lin = df_ab_lin.append(
/opt/conda/envs/freyja-env/lib/python3.10/site-packages/freyja/utils.py:248: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_ab_lin = df_ab_lin.append(
/opt/conda/envs/freyja-env/lib/python3.10/site-packages/freyja/utils.py:248: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_ab_lin = df_ab_lin.append(
Traceback (most recent call last):
  File "/opt/conda/envs/freyja-env/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/freyja/_cli.py", line 242, in dash
    make_dashboard(agg_df, meta_df, thresh, titleText, introText,
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/freyja/utils.py", line 262, in make_dashboard
    df_ab_lin = df_ab_lin[cols0]
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/pandas/core/frame.py", line 3511, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5782, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5845, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['Other'] not in index"

I do not get this error and the dashboard is generated as expected when the "--eps" flag is not raised in the demix step. 
Please find attached the two aggregate files, one that works and the other that produces the above error. Also attached is the metadata file used to run freyja dash for these. 

[metadata.csv](https://github.com/andersen-lab/Freyja/files/9104017/metadata.csv)
[aggregate_works.tsv.txt](https://github.com/andersen-lab/Freyja/files/9104018/aggregate_works.tsv.txt)
[aggregate_fail.tsv.txt](https://github.com/andersen-lab/Freyja/files/9104019/aggregate_fail.tsv.txt)

**Comment by joshuailevy** [comment]
Hi @whottel! Thanks for bringing this up. Someone else ran into the same issue actually, and it stems from the fact that I hadn't sufficiently investigated how using different values of  ```--eps``` can play out in the ```dash``` function. I'll go ahead and patch this (it's a very simple fix), but in the meantime a quick fix is just to add "Output" to the lineage list (with abundance of 0) like this:
[aggregate_fail.tsv.txt](https://github.com/andersen-lab/Freyja/files/9104888/aggregate_fail.tsv.txt)

I'll make sure to roll this out in the next release. Thanks again!

**Comment by joshuailevy** [comment]
Of course! Yeah, the dash function is still very much a work in progress, and I've been meaning to add in some functionality for more custom grouping of lineages (will definitely be included in the next release as well). This feedback is super helpful as I go about further development, thanks again.

**Comment by whottel** [comment]
Sounds good, I look forward to the next update!

**Comment by joshuailevy** [comment]
@whottel I believe this issue has been resolved in the most recent release (v1.3.9). Should now be available via conda.
