### ISSUE TITLE
Freyja Dashboard Unexpected Scaled Output

### ISSUE THREAD

**Issue by whottel** [andersen-lab/Freyja#73]
I was reviewing the "Load Sacled ..." tabs of a Freyja generated dashboard, and I was observing unexpected counts and relative proportions.
For example I used the following input files:
[metadata_test.csv](https://github.com/andersen-lab/Freyja/files/9135526/metadata_test.csv)
[aggregate_test.tsv.txt](https://github.com/andersen-lab/Freyja/files/9135580/aggregate_test.tsv.txt)

In this contrived example there are two samples both from the same site on the same day. Sample 1 has 500k copies/L and Sample 2 has 1,000K copies/L. Sample 1 is 50% BA.2 and 50% BA.4. Sample 2 is 50% BA.2 and 50% BA.5.
Therefore I was expecting to the scaled lineages to be BA.2=750K/L (50%), BA.4=250K/L (16.7%), and BA.5=500K/L (33.3%)
However, the result from freyja dashboard seems to be based on the average of the overall lineage count of 750K resulting in BA.2=375K/L (50%), BA.4=187.5K/L (25%), BA.5=187.5K/L (25%).
Is this the intended behavior?

**Comment by joshuailevy** [comment]
This is a great point(I figure you meant BA.5 is in one of the samples), and a known issue of the dashboard plotting functionality (another quick fix, which is nice). Just requires rescaling based on viral loads prior to normalization. 

The dashboard function was written with the expectation of just a single sample per day, and doesn't generalize to the case you suggest immediately. However, this is exactly the sort of normalization we use for the Omicron analysis in our [paper](https://www.nature.com/articles/s41586-022-05049-6).  Will incorporate into the dash functionality soon!

**Comment by whottel** [comment]
Apologies, edited my earlier comment to indicate BA.5 is in Sample 2.
Glad to hear this is another quick fix. The reason I bring this up is we occassionally collect multiple bottles from the same site on the same day, and I want to be sure I am interpreting the output correctly.

**Comment by joshuailevy** [comment]
This  functionality is now available via the ```--scale_by_viral_load``` flag and has now been documented in the readme. Thanks again for the reminder!
