### ISSUE TITLE
problem plot freyja v1.3.10 python 3.7

### ISSUE THREAD

**Issue by marianarias** [andersen-lab/Freyja#82]
Hi, problem plot
freyja plot archivo-demixed.tsv --output archivo-demixed.png  --lineages
does not show graph, sample coverage	22.05464334682139

**Comment by joshuailevy** [comment]
Hi @marianarias! What actually is being returned by ```plot```? Is there just a blank graph? Or no output at all?

**Comment by marianarias** [comment]
HELLO, I ALREADY UNDERSTOOD MY PROBLEM, I HAD SAMPLES WITH LESS THAN 2O COVERAGE AND THESE SAMPLES WERE NOT GRAPHED IN FREYJA 1.3.10, IN COMPARISON WITH VERSION 1.3.8, I READ YOUR INSTRUCTIONS AND IT IS ALREADY SOLVED, THANK YOU.

**Comment by joshuailevy** [comment]
Ok great!! Glad this has been solved :)
