### ISSUE TITLE
Freyja update maUtils issue with ouput path

### ISSUE THREAD

**Issue by sgsutcliffe** [andersen-lab/Freyja#83]
I've found an issue when I run Freyja update command. 

In the convert tree function, matUtils has trouble finding the output directory, it tries to output //lineagePaths.txt

When I tried running it with the -d option it fixes it
`varCmd = f"matUtils extract -i {treePath} -C lineagePaths.txt -d {locDir}"`
 -d option is the option for output directory

Weirdly this only comes up when I run from a specific server. So probably not a big issue.

**Comment by joshuailevy** [comment]
Hey @sgsutcliffe! Interesting, are you hoping to get access to the ```lineagePaths.txt``` file? Currently I have things set up to output it to the user's local directory during update as it's used for building the barcodes, but this file is removed at the end of the update step.

**Comment by sgsutcliffe** [comment]
I have freyja installed in a singularity container and I was having issues with it running on one server but not another. 
I was getting "FileNotFoundError: [Errno 2] No such file or directory: './lineagePaths.txt' " when I ran the update.
So I tried modifying the convert tree function as I mentioned in the python script and it solved it.

**Comment by sgsutcliffe** [comment]
I figured this out because when I run the python script I get:
"Writing clade paths to //lineagePaths.txt" Which did not make sense. Somewhere it was getting mixed up.

**Comment by joshuailevy** [comment]
Ah, any chance you're limited by memory on this server? There's been reports of a similar error (from the ```matUtils extract``` command getting killed) as a result of the lineagePaths.txt not getting returned.  For example: https://github.com/andersen-lab/Freyja/issues/60#issuecomment-1163665070

**Comment by sgsutcliffe** [comment]
No because I was able to run the matUtils extract no problem on its own. Also the solution to the problem was to use
matUtils extract -i {treePath} -C lineagePaths.txt -d {locDir}
The added option was this:
--output-directory (-d): Write all output files to the target directory. Default is current directory.
Without it it was trying to "Writing clade paths to //lineagePaths.txt"

**Comment by joshuailevy** [comment]
Ah, I see. Good catch. I'll modify things slightly for the next release so the user has a bit more control of where these files are generated during the update (i.e. such that they are generated in the output directory rather than the current directory).

**Comment by afonsoguerra** [comment]
@sgsutcliffe have you checked if all your needed paths are mounted inside the container? You can probably find the path you need with “readlink -f “ and add it with -B when you run the singularity container and see if it fixes it.

Incidentally, do you have that singularity recipe anywhere public?

**Comment by sgsutcliffe** [comment]
I don't think, but could be wrong, that it is the issue with paths mounted (I mount the parent directory of everything needed into /mnt) in the container. As mentioned above when I run matUtils within the container and the option -d it goes to the right directory. 

My container is not public right now, I mostly created for just my own use (not sure where I was going to be running my analysis and wanted to avoided multiple installs).
