### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'log2'

### ISSUE THREAD

**Issue by YuWang07** [andersen-lab/Freyja#87]
Dear Joshua,
Thanks for developing this useful tools. I just install the version 1.3.11 and I get the following error when I am using the freyja demix function:

 File "/home/s4519890/miniconda3/envs/freyja-env/lib/python3.10/site-packages/pandas/core/generic.py", line 5907, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'log2'
I try to converts the data type of the Series object from object to np.float64. But still not working.
I have using Evan's .bam file (Thanks for provide this file  @evantroendle) as a test and it running well with no error.  I also uploaded my bam file: https://drive.google.com/file/d/1_EUklUSMEPMxbnjz6cLSHioTfmOrIqbF/view?usp=sharing, could you please give some suggestions?

Thanks,
Yu.

_Originally posted by @YuWang07 in https://github.com/andersen-lab/Freyja/issues/50#issuecomment-1272456061_

**Comment by joshuailevy** [comment]
Dear @YuWang07, 

Apologies for the delay. I was able to run successfully process your sample using Python 3.9.13 without any issues. I ran the following commands: 

```freyja variants D1-C17_1.bam --variants d1.tsv --depths d1.depths --ref MN908947.3.fasta --refname MN908947.3```

and then 

```freyja demix d1.tsv d1.depths --output d1.output``` 

Here's that output file: 
[d1.output](https://github.com/andersen-lab/Freyja/files/9795860/d1.output.txt)

Can you try running those commands and let me know what happens? In particular, it's important to specify the reference name since the bam has multiple references in it. 

Best, 
Josh

**Comment by YuWang07** [comment]
Hi, Josh

Thanks for the help, much appreciate.
When I specific the `--refname MN908947.3`, I got the following error:

`freyja variants /scratch/project/wwvirus/YU_RO2/01.RO1/02.analysis/WWS_BAM/D1-C17_1.bam --variants d1.tsv --depths d1.depths --ref ./database/nCov.fasta --refname MN908947.3`

[E::idx_find_and_load] Could not retrieve index file for '/scratch/project/wwvirus/YU_RO2/01.RO1/02.analysis/WWS_BAM/D1-C17_1.bam'
[mpileup] fail to load index for /scratch/project/wwvirus/YU_RO2/01.RO1/02.analysis/WWS_BAM/D1-C17_1.bam

This fix after I create index file for these .bam files. 

Thanks,
Yu

**Comment by joshuailevy** [comment]
Hi Yu, 
Great! So it sounds like things are working now? If so, I'll go ahead and close the issue. 
Josh
