### ISSUE TITLE
BQ1.1 not present in UShER database upon updating

### ISSUE THREAD

**Issue by JHarrisonEcoEvo** [andersen-lab/Freyja#88]
Big fan of Freyja. I have periodically been updating the tool using 'freyja update' to ensure I have the latest and greatest usher barcodes database. I have not yet seen BQ1.1 in the database, just BQ.1.

I am wondering if this suggests there is a code issue or if the database has simply not been updated yet by the folks that curate the UShER tree for SARS-CoV-2. 

Thanks for any insights.

PS: I updated to Freyja 1.3.11 and called 'freyja update' last the morning of Oct 19, 2022.

**Comment by joshuailevy** [comment]
Hi @JHarrisonEcoEvo, 
Thanks for letting me know. This sort of issue has been popping up a bit recently, caused by there being less publicly available seq data and Freyja (currently) pulls exclusively from public sequences, leading to delays in their availability in Freyja.

Should hopefully have this issue sorted within the next day or so. Will keep you updated.

**Comment by joshuailevy** [comment]
That particular issue actually turned out to be an issue with an upstream github action that wasn't committing properly. 

Can you give it another shot and let me know if BQ.1.1 gets picked up now? v1.3.11 should work fine, didn't require any changes to Freyja.

**Comment by JHarrisonEcoEvo** [comment]
I just updated Freyja and I see all the new variants in the usher_barcodes file now. Thanks for fixing this!

**Comment by joshuailevy** [comment]
Great! Thanks again for the heads up!

**Comment by jasmine-amir** [comment]
Hi Josh,

We are also huge Freyja fans!!

I'm actually still dealing with the same thing, despite updating Freyja several times. 

The only difference is that we use the conda build [https://anaconda.org/bioconda/freyja/files]. 

I can't seem to get a version of usher_barcodes.csv newer than Oct 04 for Freyja 1.3.11, and thus we don't have BQ.1 or BQ.1.1.

Best,
Jasmine

**Comment by joshuailevy** [comment]
Hey Jasmine! 

You should be able to pull a new version of the barcodes using the ```freyja update``` command (with option to specify where you want those files with ```--outdir [your-dir-of-choice]```). Or is that not working for you? I've been a bit delayed with putting out a new conda release (been traveling quite a bit to conferences etc.), but should have a new one soon :) 

Best, 
Josh

**Comment by jasmine-amir** [comment]
Hi Josh,

The `freyja update` finally worked right after I commented out some conda commands in my user .bashrc, oops!

Sorry about that, and thank you again for Freyja (:

Best,
Jasmine

**Comment by joshuailevy** [comment]
Great! Glad it's working!
