### ISSUE TITLE
Recombinant detection

### ISSUE THREAD

**Issue by AnehEf** [andersen-lab/Freyja#91]
Hi Freyja's team,

Thanks again for your amazing tool!

Would it be possible to have the option to remove the recombinants from the analysis? I'm not questioning the existence of recombinants, I'm just skeptical of the relevance/accuracy of calling recombinants from wastewater using short-read sequencing.
Thanks, 

Adelaide

**Comment by joshuailevy** [comment]
Hi @AnehEf! 

There isn't currently a built-in option to do this, but it can be achieved quickly by using the ```--outdir``` option of ```freyja update``` to return the barcodes to a directory of your choice. Once you've done that, you should be able to filter out any rows of the table that have an X in the lineage name (first column) and pass the new resulting barcode csv into ```freyja demix``` using the ```--barcodes``` option. 

If that's not quite clear, let me know. Happy to provide you with a quick script to accomplish this. 

Josh

**Comment by AnehEf** [comment]
Thank you very much Josh. It is super clear. 
Best, 

Adelaide
