### ISSUE TITLE
Freyja plot error

### ISSUE THREAD

**Issue by pratibha-kadam** [andersen-lab/Freyja#94]
Hello,
I am using Freyja for wastewater samples analysis. Its a really good tool for the abundance of the lineages from mixed samples and also gave me the output for my previous analysis.

But now I have few samples for that I am running Freyja it is generating .demix and aggregated.tsv file but when I try to plot that it is throwing an error. 
To check is there something wrong with the code I run the tool on previous data file it worked fine. I am not able to resolve the error.
Hope you can help me :)

Attaching the files below

1. Input fastq file:
[barcode84.fastq.gz](https://github.com/andersen-lab/Freyja/files/9927451/barcode84.fastq.gz)

2. demix file output:

barcode84_freyja.variants.tsv
summarized	[('BA.2.75* [Omicron (BA.2.75.X)]', 0.9999999999999806)]
lineages	BA.2.75
abundances	1.00000000
resid	13.565059442734382
coverage	1.7723974183192321

3. lineage file and summarise file
[barcode84_freyja_boot_lineages.csv](https://github.com/andersen-lab/Freyja/files/9927484/barcode84_freyja_boot_lineages.csv)

[barcode84_freyja_boot_summarized.csv](https://github.com/andersen-lab/Freyja/files/9927491/barcode84_freyja_boot_summarized.csv)

4. Screenshot of Output
![Screenshot from 2022-11-03 16-08-32](https://user-images.githubusercontent.com/88572259/199700613-2f453d45-922c-4bca-9e68-5fe36453c847.png)

**Comment by joshuailevy** [comment]
Hi! 

It seems like you've got an issue with the format of your aggregated output file. Is it possible for you to send that as well? If there's only one demix result in your aggregated file, that may be causing some issues with dataframe format upon reading in the file. 

Josh

**Comment by pratibha-kadam** [comment]
Hey Josh,
Thanks for the response.

PFA the aggregated file (in .xls format)
[barcode84-aggregated.xls](https://github.com/andersen-lab/Freyja/files/9967477/barcode84-aggregated.xls)

**Comment by pratibha-kadam** [comment]
Hello there,
Please someone revert on this asap. I need it in my analysis.

Thanks

**Comment by joshuailevy** [comment]
Seems like your output is in a weird format. Can you provide the bed file corresponding to the amplicon scheme you used so this issue can be reproduced from scratch? Also, it's worth noting that your coverage is quite low here (in general, even samples <50% coverage should probably not be included)

**Comment by pratibha-kadam** [comment]
This problem is with some samples for other samples it is working fine and generates plot.

PFA the primers bed file in txt format
[articV4_bed.txt](https://github.com/andersen-lab/Freyja/files/9979238/articV4_bed.txt)

**Comment by joshuailevy** [comment]
Ah... this is just because the default minimum coverage used for plot is 60% (10x). Setting "--mincov" equal to something less than the coverage you've got for that sample should solve this problem. That said, the sample is quite low coverage and may not yield the most reliable results.

**Comment by pratibha-kadam** [comment]
Thanks for the information. I could plot the graphs now. can you please
tell me what is that coverage is? is it genome coverage or something else?




Thanks and Regards
Pratibha

**Comment by joshuailevy** [comment]
Great! The "coverage" is 10x genome coverage (the percentage of sites with at least ten reads).
