### ISSUE TITLE
Freyja Variants creates unregistered bases

### ISSUE THREAD

**Issue by EESI-jv545** [andersen-lab/Freyja#96]
Hi everyone,
I'm currently using Freyja in a pipeline that processes a set of 414 COVID-19 samples, and I am able to get output TSV files that give positions on the single nucleotide variants. I noticed how the TSV files have positions with alternate base like -T or +C, but when I downloaded these as CSV files, their cells would only give errors saying "#NAME?". If someone could tell me why are there +/- bases, as well as how I can fix the #NAME? issue, that would be great!

The code and files should be attached too; I couldn't get the TSV file uploaded since Github doesn't support that format, but I pasted a screenshot of the file with some of the positions listed

[TWC3_S126_variants.csv](https://github.com/andersen-lab/Freyja/files/9933178/TWC3_S126_variants.csv)
![image](https://user-images.githubusercontent.com/115170707/199839810-bc580220-84de-4c3f-8559-2626e9abc1ca.png)

`#!/bin/bash

refStrain=wuhan.fasta

FilesLoc=./ARGONNE_FILES/ARGONNE_FASTQ

PrimerLoc=qiaseqdirectsarscov2primersfinal.bed
CsvResults=./all_freyja/all_csv
#conda activate freyja

prefix=$1
prefixdir=all_freyja/all_temp/$prefix
mkdir $prefixdir

csvdir=$CsvResults/$prefix
mkdir $csvdir

Ivar_Dir=all_freyja/Ivar_Varians_output/$prefix
mkdir $Ivar_Dir

	bwa-mem2 mem $refStrain $FilesLoc/${prefix}_R1_001.fastq $FilesLoc/${prefix}_R2_001.fastq > $prefixdir/$prefix.sam

	samtools view -S -b $prefixdir/$prefix.sam > $prefixdir/$prefix.bam

	samtools sort -o $prefixdir/$prefix.sorted.bam $prefixdir/$prefix.bam

	samtools index $prefixdir/$prefix.sorted.bam

	ivar trim -i $prefixdir/$prefix.sorted.bam -b $PrimerLoc -p $prefixdir/$prefix.trimmed

	samtools sort -o $prefixdir/$prefix.trimmed.sorted.bam $prefixdir/$prefix.trimmed.bam

	freyja variants $prefixdir/$prefix.trimmed.sorted.bam --variants $prefixdir/${prefix}_variants.tsv --depths 
	
	freyja demix $prefixdir/${prefix}_variants.tsv $prefixdir/$prefix.depths --output $csvdir/$prefix.tsv`

**Comment by joshuailevy** [comment]
Hi @EESI-jv545! 

The +/-[bases] entries indicate insertions and deletions. At the moment these are not used in standard freyja workflows, which currently only use SNPs, but can (and will) be used in lineage barcoding in the future. My guess is the the "#NAME" is likely due to Excel trying to process some of these attributes, but doesn't understand the syntax. I haven't run into this issue before, but it could be worth trying libreOffice Calc or Numbers for manual investigations of those tsv files.

**Comment by EESI-jv545** [comment]
Awesome, I'll check them out. Thank you so much!
