### ISSUE TITLE
Freyja update and custom files clarificaiton

### ISSUE THREAD

**Issue by gholden3** [andersen-lab/Freyja#97]
Hi Josh! 

Could you please confirm my understanding of how I can use the freyja update and then demix commands together? My setup is I'm using the conda package and I would like to run the update command once per day, then grab the output files and send those files to a bunch of parallel processes to use without all those workers having to call freyja update as well. 

My understanding is I could call "freyja update" and specify an --outdir. Then I could take the usher_barcodes.csv and lineages.yml that get written there and then call freyja demix { path to freyja.variants.tsv} { path to freyja.depths} --output {path to output freyja.demix} --barcodes usher_barcodes.csv --meta lineages.yml

Could you confirm this is the case? This will fully update all needed reference files for freyja?

Thanks!!

**Comment by joshuailevy** [comment]
Hi! 

That's pretty much it. The update operation will provide you with new barcodes and mappings from lineages-> VOCs (curated_lineages.json), and then you should be up-to-date.  

 The ```lineages.yml``` file is actually not the one you want to supply for the ```--meta``` option though. You'll want to provide the ```curated_lineages.json``` file there (the lineages.yml output is somewhat recent and really intended for the downstream plotting/dash functionality, and I'm now realizing this is a bit confusing-- I'll make sure to clarify this in the documentation). Of course, you don't actually need to specify an ```--outdir``` if you don't want to, but then all of the updated files will end up in your freyja package directory/repo's data folder. 
 
Hope that helps! 
Josh

**Comment by gholden3** [comment]
Thank you! I will pass in curated_lineages.json.
